### ISSUE TITLE
--wsdl-genautoload=false also controls creation of sample.php file (console mode)

### ISSUE THREAD

**Issue by Geabulek** [WsdlToPhp/PackageGenerator#10]
I was assuming that --wsdl-gentutorial=[true/false] was controlling the creation of sample.php file.

The behaviour I get is --wsdl-genautoload=true generates autoload and sample.php, --wsdl-genautoload=false does generates neither autoload.php not sample.php.

Is this is a bug, I would be a minor one obvisously.
BR
Geabulek

**Comment by mikaelcom** [comment]
The bug is here https://github.com/WsdlToPhp/PackageGenerator/blob/develop/Generator/Generator.php#L557 :smile:
