### ISSUE TITLE
Send Multiple Elements of the same name

### ISSUE THREAD

**Issue by SerethiX** [WsdlToPhp/PackageGenerator#100]
Hello folks,

I'm relatively new to SOAP and I need to talk to a WS that requires all the data in one big request as complex types.

I can Talk to the Endpoint when all objects just occur one time. But I can't get it to work with multiple of the complex types, which is mandatory.

Is this possible with an SDK generated by this tool and just the wsdl file is wrong?
Or do I need to configure the Generator another way?

Thanks in advance!

**Comment by mikaelcom** [comment]
If the wsdl allows multiple element of the same type, it should be possible to do what you describe.

Is it possible to have he WSDL?

**Comment by SerethiX** [comment]
Unfortunately not :/

But I have the piece from the xsd, where this type get's defined.

https://pastebin.com/QWAgmibx

There are also complexType Definitions in another xsd file:
```
	<xs:complexType name="mav.SignaturbeschreibungTyp">
		<xs:complexContent>
			<xs:restriction base="business:mav.SignaturbeschreibungTyp">
				<xs:all>
					<xs:element ref="BdIntId"/>
					<xs:element ref="Position" minOccurs="0"/>
					<xs:element ref="Funktion" minOccurs="0"/>
					<xs:element ref="Vorname" minOccurs="0"/>
					<xs:element ref="Nachname" minOccurs="0"/>
					<xs:element ref="Geschlecht" minOccurs="0"/>
					<xs:element ref="Titel" minOccurs="0"/>
				</xs:all>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
```

Can you help me with these partial information?

**Comment by mikaelcom** [comment]
Even privately at contact@wsdltophp.com after anonymizing the endpoints ?

In the meantime and for the public view, it depends if the property that has to be a multiple of complex types is declared as a multiple. It is normally done with the usage of the `minOccurs` attribute. Could you precise the property that has to be an array? Could you provide too the generated classes that are used?
Nevertheless, you can simply try to pass an array of objects instead of passing a unique object.

**Comment by SerethiX** [comment]
That would be
- <xs:element name="Inhalt" minOccurs="0">
- <xs:element name="Bilddatei" minOccurs="0">
- <xs:element name="Signaturbeschreibung" minOccurs="0">
- <xs:element name="Layout" minOccurs="0">

And that's where I don't get it.
I expect the object "Mitarbeiterverwaltung" to allow passing Arrays of Objects.

https://pastebin.com/iJSrL0ZC

**Comment by mikaelcom** [comment]
It would be really simplier to have the WSDL and the details of the operation you need to call to be able to give you a good response

**Comment by SerethiX** [comment]
Hello Folks, we went on to another Solution, but I will try to make it possible to get the WSDL here without the critical parts.

**Comment by mikaelcom** [comment]
I hope the other solution is not another generator project 😟 , please share if you can

**Comment by mikaelcom** [comment]
I'm closing this issue as a new release has been created. This new release will maybe help you fix your issue.

If not, feel free to reopen this issue,

thx
