### ISSUE TITLE
Empty namespace in composer.json file for autoloader

### ISSUE THREAD

**Issue by brainyprb** [WsdlToPhp/PackageGenerator#105]
There is empty namespace for auto-loading classes which decreases code performance  and also interferes while adding custom namespaces. 

{
    "name": "providr-packages/package-303",
    "description": "Package generated from main.wsdl using wsdltophp/packagegenerator",
    "require": {
        "php": ">=5.3.3",
        "ext-soap": "*",
        "wsdltophp/packagebase": "~1.0"
    },
    "autoload": {
        "psr-4": {
            "": "./src/"
        }
    }
}

**Comment by mikaelcom** [comment]
What would you propose then?

**Comment by brainyprb** [comment]
It would be easy to implement my custom classes if you can add a namespace instead of leaving it empty.
I donot know how to update all of the code files  if I add the namespace myself.
It will be convenient if the package generator implements it.
And is providr.io updated with latest changes made on package generator in github ?
Please consider my request if this is a progressive change.

Thanks,
Pushpa Raj

**Comment by mikaelcom** [comment]
You can already set a namespace for the generated classes using the [namespace](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#namespace) option (`Use your namespace prefix` on [providr.io](https://providr.io)), maybe this is what you're looking for?

Otherwise, all I can think of would be to specifically define all the possible namespaces such as:
```json
{
  "name": "providr-packages/package-303",
  "description": "Package generated from main.wsdl using wsdltophp/packagegenerator",
  "require": {
    "php": ">=5.3.3",
    "ext-soap": "*",
    "wsdltophp/packagebase": "~1.0"
  },
  "autoload": {
    "psr-4": {
      "StructType\\": "./src/StructType/",
      "ArrayType\\": "./src/ArrayType/",
      "EnumType\\": "./src/EnumType/",
      "ServiceType\\": "./src/ServiceType/"
    }
  }
}
```

Except that the ClassMap class would still not have a namespace so it would need to add this sort of thing:
```json
{
  "autoload": {
      "files": ["src/MyLibrary/functions.php"]
  }
}
```

Currently I don't think it's crucial according to the fact that you can set your own namespace.

What do you think?

**Comment by mikaelcom** [comment]
The [providr.io](https://providr.io) platform currently uses the 2.6.0 release 😞

**Comment by brainyprb** [comment]
Yes, using the namespace function solved my issue. Thank you very much for pointing this out.
And do you own providr.io platform , I would like to message them to update to latest release.

Again thank you very much for this handy tool , it has made my life easier with SOAP.

Thanks,
Pushpa Raj

**Comment by mikaelcom** [comment]
> And do you own providr.io platform , I would like to message them to update to latest release.

Yes I do 😉

**Comment by brainyprb** [comment]
Okay thats very nice, I hope you till update the package soon.

**Comment by mikaelcom** [comment]
If you like it, you should start it 😉

**Comment by mikaelcom** [comment]
@brainyprb the platform [providr.io](https://providr.io) has been updated with the latest version of the generator just a minute ago 😄

**Comment by brainyprb** [comment]
Thank you , thats a good notification I got today 👍
