### ISSUE TITLE
Multiple services, common types

### ISSUE THREAD

**Issue by tomasruud** [WsdlToPhp/PackageGenerator#106]
Hi! I'm trying to generate a package from multiple services, which shares some common types for authentication etc. The way I'm currently doing this is by looping the generator over the different services, and let the output go to the same folder. Is this the preferred way to solve this problem?

**Comment by mikaelcom** [comment]
If I understand well, you would like to generate a unique package based on multiple Web Services? Personally I always prefer to generate a package per Service as even if they share types, (ex: OTA Web Services), it allows to have proper classes per package.

There is currently no implementation of taking into account multiple WSDL for the same package as it's not a common usage. For example, it you have multiple Web Services with same operation name and same operation's parameters, it will be very hard to differentiate them. Currently, same operation name with different signature is handled and this is not a common case already.

Maybe you have thought about that and other issues, please share your thoughts.

**Comment by tomasruud** [comment]
I think the main problem we are facing is how the service we are working with is built. I'm not that experienced with SOAP, but to me it doesn't seem like the guys that built the service is either, so I guess there are some bad practices that makes things more difficult than necessary.

Also some times the service just returns a `dataset`, is it possible to generate classes from a dataset like this, or do I have to write them manually?

**Comment by mikaelcom** [comment]
It depends on the dataset, if it is not defined in the WSDL or not. If you can share the WSDL or send it to me at contact@wsdltophp.com, I'll tell you what you can expect or not,

**Comment by mikaelcom** [comment]
As I can see in the files you sent me, there is now way to get PHP objects automatically from the SOAP response. You have to handle the response dataset with the `getLastResponse(true)` call in order to walk through the data using the DOMDocument returned by the previous call.
