### ISSUE TITLE
Gather method "none" generates only a single service file with one single method

### ISSUE THREAD

**Issue by cheindl** [WsdlToPhp/PackageGenerator#112]
When using the gather method "none" there is only generated one single service file which contains only one (last?) method definition. All other methods are omitted. Service name is also not as expected.

**Comment by mikaelcom** [comment]
Indeed, this bug has been introduced in this commit https://github.com/WsdlToPhp/PackageGenerator/commit/0f636ffc666719b4035248a820aebbcc3a27bbe3#diff-161c857eea88b14b50a5903fbe6296fa, my bad!

To be frank I think a few people used this option value but as it is provided, you expect it to be working well 😉 

It'll be fixed soon,
