### ISSUE TITLE
How to generate package

### ISSUE THREAD

**Issue by rps-repo** [WsdlToPhp/PackageGenerator#113]
I don't understand how to generate a package.  I am using codeigniter framework and have installed this library using composer.  In the Usage section it has a subsection for In a project.  When I try to use this code I get an error that no class GeneratorOptions is found.  I searched the source and see many using 

`use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
`
I added this and now get the error:

Message: The "Generator" class is reserved for internal use and cannot be manually instantiated

I would try using command line but I have no idea what exactly I am supposed to execute and from where.  Composer installed the library in /home/myuser/public_html/application/vendor/wsdltophp.  Where should I execute the code below?

```
wsdltophp generate:package \
    --urlorpath="http://developer.ebay.com/webservices/latest/ebaySvc.wsdl" \
    --destination="./MySdk" \
    --composer-name="myproject/mysdk" \
    --force
```

**Comment by mikaelcom** [comment]
I'm :disappointed:, I thought the doc was ok since its last rewriting but it seems we can always do better!

**In your project**
If you use it in your project with composer, be sure that composer dumped the autoload correctly. Then if you used the code below it should work:

```php
use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
use WsdlToPhp\PackageGenerator\Generator\Generator;

$options = GeneratorOptions::instance(/* '/path/file.yml' */);
$options
    ->setOrigin('http://developer.ebay.com/webservices/latest/ebaySvc.wsdl')
    ->setDestination('./MySdk')
    ->setComposerName('myproject/mysdk');
// Generator instanciation
$generator = new Generator($options);
// Package generation
$generator->generatePackage();
```

**Using the command line**
The command line does not need to use composer, you have to strictly follow the section [With command line](https://github.com/WsdlToPhp/PackageGenerator#with-command-line) in the readme.

Let me know how it goes, thx

**Comment by rps-repo** [comment]
Thanks for the help!!  I was able to get the package to generate but I am having some trouble with composer I think.  Since my project is already using composer I generated the package using these options:

```
        $options = GeneratorOptions::instance();
        $options
                ->setOrigin('/home/osqbdev/public_html/wsdl/onesource.wsdl')
                ->setDestination('/home/osqbdev/public_html/application/vendor/onesource')
                ->setNamespace('Onesource')
                ->setStandalone(FALSE);
        // Generator instanciation
        $generator = new Generator($options);
        // Package generation
        $generator->generatePackage();
```
This works OK and files where generated and placed in the composer dir. 

In my composer.json I set this:

```
  "autoload": {
    "psr-4": {
      "Onesource\\": "/onesource/src"
    }
  }
```
And then did composer update.  I confirmed that the autoload_psr4.php contains this after update.

`'Onesource\\' => array('/onesource/src'),`

But in autoload_static.php it has

```
        'Onesource\\' => 
        array (
            0 => '/onesource/src',
        ),
```

but it needs to be:

```
        'Onesource\\' => 
        array (
            0 => __DIR__ . '/..' . '/onesource/src',
        ),
```

I manually changed autoload_static.php and the sample code in tutorial.php works.  Do you know what I am missing in my composer.json so composer will put the correct path in autoload_static.php?

**Comment by mikaelcom** [comment]
I think this is not a good idea of generating the package under the vendor directory as it should be dedicated to dependencies defined in the require(-dev) sections of your composer.json file.

The generated package should be generated under a proper directory into your app code. Then add the path in the composer.json file as you did then run the `composer dump-autoload` command line.

**Comment by Gemorroj** [comment]
@mikaelcom in fact, `wsdltophp` need require without *-dev*, because generated code use https://github.com/WsdlToPhp/PackageBase.
or need add to faq example how to add the `PackageGenerator` to `composer.json`

**Comment by Gemorroj** [comment]
@rps-repo see [FAQ](https://github.com/WsdlToPhp/PackageGenerator/wiki/FAQ), block "So you have to compose your composer.json such as"...
and I just use `classmap`, not `psr-4` in composer for autoload generated code.

**Comment by Gemorroj** [comment]
> I'm 😞, I thought the doc was ok since its last rewriting but it seems we can always do better!
I think you are paying too much attention to generating the code of the phar archive.
And far too little attention generate code using the internal api.

**Comment by rps-repo** [comment]
Think I have everything worked out.  Thanks for all your help and your hard work on this library!

**Comment by mikaelcom** [comment]
@rps-repo and @Gemorroj: thanks for your feedback, so if you have any advice about what SHOULD/MUST be written/documented, please let me know 😉

**Comment by mikaelcom** [comment]
I updated the options info https://github.com/WsdlToPhp/PackageGenerator/wiki/Options/_compare/2c191e11e55f156ebfdd66fa4e36fe7dc22e4f31...893f75ef701eace3a7c63da4dcc9f9bea0c05bc0
