### ISSUE TITLE
AbstractStructBase implement JsonSerializable

### ISSUE THREAD

**Issue by Gemorroj** [WsdlToPhp/PackageGenerator#114]
AbstractStructBase need implement [JsonSerializable](http://php.net/manual/en/jsonserializable.jsonserialize.php) interface.
In my case this is necessary for logging data.

Example implementation:
```php
abstract class AbstractStructBase implements StructInterface, JsonSerializable
{
    public function jsonSerialize()
    {
        $data = \get_object_vars($this);
        return $data;
    }

    // other methods
}
```

**Comment by mikaelcom** [comment]
- First, if this is about the AbstractStructBase class, you should create an issue at the [PackageBase ](https://github.com/WsdlToPhp/PackageBase)project,
- Second, you could use your own implementation of the AbstractStructBase by using your own parent classes. If you read the [Classes inheritance](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#classes-inheritance) section of the Options page in addition to the PackageBase readme about the [AbstractStructBase class](https://github.com/WsdlToPhp/PackageBase#abstractstructbase), it should work, shouldn't it?

**Comment by Gemorroj** [comment]
1. yes. sorry
2. yes, but nothing prevents to implement `JsonSerializable` in the base project.

**Comment by Gemorroj** [comment]
see [PackageBase/issues/13](../../PackageBase/issues/13)
