### ISSUE TITLE
Use package with WS Security

### ISSUE THREAD

**Issue by rps-repo** [WsdlToPhp/PackageGenerator#115]
Is there an example anywhere showing how to use the generated package with your WsSecurity library?

**Comment by mikaelcom** [comment]
The WsSecurity readme show a [basic sample](https://github.com/WsdlToPhp/WsSecurity#how-to-use-it).

If we imagine you have a generated ServiceType class named `Get` instantiated as `$get = new \ServiceType\Get()`, then you can set the WsSecurity header such as:
```php
$get->getSoapClient()->__setSoapHeaders(WsSecurity::createWsSecuritySoapHeader('login','password'));
// setSoapHeader* methods within the ServiceType class, if exist/generated, must be called after the __setSoapHeaders call
// $get->setSoapHeaderAuthentication(new \StructType\AuthenticationData());
```

**Comment by rps-repo** [comment]
Thanks!
