### ISSUE TITLE
www.wsdltophp.com is down!

### ISSUE THREAD

**Issue by phpclub** [WsdlToPhp/PackageGenerator#116]
www.wsdltophp.com is down!

**Comment by mikaelcom** [comment]
Hi there,

It's good to know that you're using it. I know that [providr.io](https://providr.io) is not as featured as wsdltophp.com, nevertheless, did you give it a try? Feel free to give me feedback about your usage of wsdltohp.com 😉 .

From here, France, it's working/reachable, no issue in particular. What do you get when you ping it? Maybe you IP has been blocked by our firewall 😮

**Comment by phpclub** [comment]
Its up now.
