### ISSUE TITLE
SoapClient should not be static

### ISSUE THREAD

**Issue by cheindl** [WsdlToPhp/PackageGenerator#117]
I have a project with several, different Webservices (different WSDLs) where i generated client classes with the generator.

When i try to use multiple services within one php runtime, i get problems as each client shares the same instance of AbstractSoapClientBase::soapClient.

IMHO there are two solutions:
- AbstractSoapClientBase::soapClient will be made an instance variable
- AbstractSoapClientBase::soapClient should be defined some where further down in the hierarchy (per WSDL client)

**Comment by mikaelcom** [comment]
I understand your issue. First thing first, could you create this issue at the [PackageBase](https://github.com/WsdlToPhp/PackageBase/issues) project as it does concern the PackageGenerator project actually.

**Comment by cheindl** [comment]
In a way it also affects the PackageGenerator project, as client generation must be changed, if changes are made in AbstractSoapClientBase. I created now [PackageBase#15](https://github.com/WsdlToPhp/PackageBase/issues/15) to address the issue in PackageBase project.
