### ISSUE TITLE
PackageGenerator is not extendable, make classes attributes and methods protected

### ISSUE THREAD

**Issue by ustmaestro** [WsdlToPhp/PackageGenerator#119]
Today I try to extend PackageGenerator classes to build some custom functionality on top of this library  by extending classes without changing the original files and I've stack with private methods and attributes of classes.
Why not change all attributes and functions to protected instead of private, because  the main purpose of this, is to generate classes from wsdl's.

**Comment by mikaelcom** [comment]
If your functionalities are useful to the generator, it could be implemented in it. If it's more private, then yes, private properties/methods could be changed to protected.

Let me know what you aim to do if you can,

**Comment by ustmaestro** [comment]
Thank you @mikaelcom for your reply and for our job!
My functionality is more project specific like Sabre Avia, Hotel webservices (hard to work with these and has many duplicate class definitions with different attributes in different registers like Tax\@amount and Tax\@Amount), and many other things that must be checked.
So I want to change a bit the way that some classes must be generated. 

Second my classes must extend a base class with extra code. I thought that you library can help me.
I've checked many packages on Github but no one work as expeted so now I try to achieve my result with yours package (most popular and maintainable) by extending it.

I will think about what functionality can be useful and implemented (ex. BaseClass).

**Comment by mikaelcom** [comment]
> Second my classes must extend a base class with extra code

If you talk about the generated classes, then you should be able to do it using the [class inheritance options](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#classes-inheritance)

If you can, make a pull request as I don't have much time to the project right now,
