### ISSUE TITLE
Auto-Adding id="ref#" attribute

### ISSUE THREAD

**Issue by mihai-mocanu** [WsdlToPhp/PackageGenerator#12]
Can you please help me understand why this:

```
$roomStay->setRoomRates(new RoomRatesType(
            array(
                new RoomRateType(
                    $roomRate->getRatePlanInfo()->getCode(),
                    $roomRate->getRoomInfo()->getCode(),
                    new RatesType($rates),
                    $roomRate->getRatePlanInfo()->getPromotionalCode()
                ),
            )
        ));
```

results in this:
```
<ns1:RoomRates id="ref1">
   <ns1:RoomRate RatePlanCode="RATE" RoomCode="DBL">
      <ns1:Rates>
         <ns1:Rate From="2015-08-14" To="2015-08-17">
            <ns1:Base AmountAfterTax="200.00" AmountBeforeTax="0" CurrencyCode="ABC"/>  
         </ns1:Rate>
      </ns1:Rates>
   </ns1:RoomRate>
</ns1:RoomRates>
```

and how can I remove the id="ref1" attribute

Thank you very much.

**Comment by mikaelcom** [comment]
Is it possible to provide the WSDL? Then the whole XML request?

**Comment by mihai-mocanu** [comment]
@mikaelcom Sorry for the late answer, but that is no longer needed and I am going to explain why.

The problem was an underlying behavior of the PHP SoapClient. If you have objects and you clone them, PHP doesn't make a deep copy of the object, but a shallow one. When you add those object to the Soap Request it builds references between the original and the copied object. The best solution I've found so far was not to clone the object, but build new ones every time ... still this is not quite good when talking about performance.
More info here: http://stackoverflow.com/questions/9744442/php-soapclient-creating-xml-references-for-identical-elements-makes-it-unaccept

Thank you for your time!

**Comment by mikaelcom** [comment]
Thanks for the explanation!
