### ISSUE TITLE
Add option to save wsdl locally

### ISSUE THREAD

**Issue by ustmaestro** [WsdlToPhp/PackageGenerator#120]
A good idea is to have a local copy of wsdl and all xsd.
I there a option to have wsdl files saved locally.
If not I can contribute and add one )).

**Comment by mikaelcom** [comment]
There is currently no option to save the WSDL and its schemas locally.

Frankly, I thought about this option but I never implemented as I wanted to extract the [WsdlHandler](https://github.com/WsdlToPhp/PackageGenerator/tree/develop/src/WsdlHandler) class into a standalone project (as the DomHandler classes). Then I would have implemented a `save` method that would have allowed to save the WSDL and its schemas locally. But it would need to use the parsers defined in the [Wsdl Parses](https://github.com/WsdlToPhp/PackageGenerator/tree/develop/src/Parser/Wsdl) folder as they work perfectly to extract the external schemas.

So maybe the other option would be to created a project that holds the WsdlHandler classes and the Wsdl parser classes without having the knowledge of the PackageGenerator class (which the case currently).

 Maybe starting small (in the PackageGenerator project) then improving it later is a better solution.

Let me know how you thought you would do.

**Comment by ustmaestro** [comment]
In GeneratorOptions an option to save or not schemas default to false and a folder option for schemas. 
In Generator class there is an method getUrlContent($url) to get content, if url is used then if is option to save is enabled (true) save content of schema to the file.

**Comment by mikaelcom** [comment]
If you feel comfortable enough to implement this, go ahead 😉 as I'm not really available for the project right now,

**Comment by ustmaestro** [comment]
ok tomarrow I will create a PR

**Comment by mikaelcom** [comment]
merged in [2.9.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.9.0)
