### ISSUE TITLE
WS Security Header

### ISSUE THREAD

**Issue by vortek** [WsdlToPhp/PackageGenerator#122]
Hello,
How do I add a WS Security Header with Username, Password, Created and Nonce?
Thanks

**Comment by mikaelcom** [comment]
take a look to https://github.com/WsdlToPhp/WsSecurity and let me know if you need more information,

**Comment by vortek** [comment]
I actually tried it first but i need to encrypt the created aswell... Is there a way to pass my own username, password, created and nonce values?

The server requires:
Encrypt with: AES / ECB / PKCS5Padding 
Encode with: Base64
Thanks

**Comment by vortek** [comment]
Got it to work with 
$soap_header = new SoapHeader('http://schemas.xmlsoap.org/ws/2012/12/secext',	'Security',	new SoapVar($xml, XSD_ANYXML), true);
$get::getSoapClient()->__setSoapHeaders($soap_header);
Thanks for the help!
