### ISSUE TITLE
Class with same attributes in different registers, breaks constructor and setters

### ISSUE THREAD

**Issue by ustmaestro** [WsdlToPhp/PackageGenerator#123]
In my case was generated a class with same attributes but different register. This is because complexType is defined in different namespaces and generated class is a combination of both.
Example:
```
 class FlightSegment
{
  public $flightNumber;
  public $FlightNumber;
}
```
The problem is that this sort of classes have a broken constructor, because all constructor params are lcfirst.
Same with setters and getters.

**Comment by mikaelcom** [comment]
fixed in [2.9.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.9.0)
