### ISSUE TITLE
classmap and namespaces are wrong when not using a prefix

### ISSUE THREAD

**Issue by ceeram** [WsdlToPhp/PackageGenerator#13]
generated namespace for the classes:
`namespace MyNamespace\;` which should not have a trailing slash,

also in the classmap the same problem is there:
`'ArrayOfstring' => '\MyNamespace\\ArrayType\ArrayOfstring',`

This forces me to use a prefix, while using namespaces by itself already avoids the need to prefix classnames already.

**Comment by mikaelcom** [comment]
Actually, preifx is required (even if it is not functionnaly required yet, this will raise an exception soon) because it prevents error such as generating classes with PHP reserved keywords.

So instead of generating renamed struct name like List_ for List, we can surely generate ApiList without any problem.

What do you think ?

**Comment by ceeram** [comment]
Makes sense, i dont understand though why the prefix is appended to the chosen namespace.
When using both options i would get something like this:
`'ArrayOfstring' => '\MyNamespace\MyPrefix\ArrayType\MyPrefixArrayOfstring',`

while i would expect it to be:
`'ArrayOfstring' => '\MyNamespace\ArrayType\MyPrefixArrayOfstring',`
in the case of using both.

Additionally i might want to use a namespace using a vendorname and a package name, yet i would want to use something else for prefixes:
`--wsdl-namespace=="Vendorname\Packagename" --wsdl-prefix="NotReserved"`

resulting in:
`'ArrayOfstring' => '\Vendorname\Packagename\ArrayType\NotReservedArrayOfstring',`

**Comment by ceeram** [comment]
additionally the same applies to the generated composer.json file. The prefix to avoid having reserved names for classes is now used in the package name:
`"name": "wsdltophp/generated-myprefix",`
while i would prefer:
"name": "vendorname/packagename",
here.
I understand you are not forced to use namespaces that contain of both a vendor and package name, still i would try to default to using the namespace as composername if possible. If the vendorname consists of only one name, it could fallback to something like:
'namespace/prefix' or 'prefix/namespace' perhaps.
Ofcourse one can easily edit the generated composer name, still having better defaults could help i think.

**Comment by ceeram** [comment]
Note, there will be people starting to use "your" wsdltophp vendorname and there will be people submitting that to packagist, which is something most vendors would like to prevent and possibly sometime in the future packagist won't allow such thing anymore. For that reason alone i would pick a different default composer name for generated packages

**Comment by mikaelcom** [comment]
The composer file is something I did not really think much about as some will not need it (using non standalone mode) and some will use it.

So I will certainly review it, thanks,

**Comment by ceeram** [comment]
I just started using this project, not sure what you mean with standalone mode? I use this generator to create a package i can use as vendor package in another application.
Also the autoload section is missing, your tutorial.php includes the autoload, but php classloader isnt able to find the generated classes because of this.

Adding this to composer.json and running `composer dump-autoload` made that part work:
`
    "autoload": {
        "psr-4": {"MyNamespace\\MyPrefix": "./"}
    }
`

**Comment by mikaelcom** [comment]
Standalone mode is introduced with the RC01 release as the generated classes inherit from classes contained by a dependency package that can be either installed in the vendor directory within the generated package directory or included in your main composer.json file.

If you could put the whole composer.json file that would be correct depending on the cases, I'll be glad :smile:

**Comment by ceeram** [comment]
I still don't understand fully what you mean. PackageGenerator (which could just as well have been a .phar) creates a package with classes and a classmap etc. The created package has a dependency on wsdltophp/packagebase. I might better ask how would you not use it as standalone?
The created package is by itself a standalone package to me.

**Comment by ceeram** [comment]
I got this from the readme:

 If you're not using the standalone mode, you must add wsdltophp/packagebase: dev-master in your main composer.json file.

I understand you need to add that dependency if you locate the created package somewhere in your application, still there wont be no autoloading of those classes, unless you also tell your main composer.json where to find these "MyVendorName\\MyPrefix" namespaced files?

**Comment by ceeram** [comment]
One other note, i would prefer suffixes over prefixes personally, as autocomplete in the IDE works a lot better with that. In order to get autocomplete really providing helpfull info i currently have to type MyPrefixArr....

**Comment by mikaelcom** [comment]
**To sum up class naming/namespacing**
- Option prefix (existing one): should prefix the generated class
- Option suffix (**new to be added**): should suffix the generated class
- Option namespace (existing one): if specified, should be the main namespace to access the classes. Currently the prefix is used in the namespace even if the namespace is defined, this'll be removed

**REQUIREMENTS**
- At least a suffix or a prefix MUST be defined to ensure non usage of a reserved PHP keywod for the class name. The two can be specified at the same time too.

**CASES**
If we have a ```List``` struct, the class is named such as:
- **Prefix alone**: \\{Prefix}\\{Prefix}List => \Api\ApiList
- **Prefix + Namespace**: \\{Namespace}\\{Prefix}List => \My\Project\ApiList
- **Prefix + Namespace + Suffix**: \\{Namespace}\\{Prefix}List{Suffix} => \My\Project\ApiListProject
- **Namespace + Suffix**: \{Namespace}\List{Suffix} => \My\Project\ListProject
- **Suffix alone**: \\{Suffix}\\List{Suffix} => \Api\ListApi

Does it match what would be more logical to you? The goal is to provide the more generic and wider behavior that can be possible, this is why I keep the prefix option as it behaves currently.

**Comment by ceeram** [comment]
Sounds like a step in the right direction and would make me happy :)

On the other hand we wouldnt need a single prefix/suffix at all, when all classes just get appended with their type:
ListStruct
SomeService
etc

**Comment by mikaelcom** [comment]
> On the other hand we wouldnt need a single prefix/suffix at all, when all classes just get appended with their type:
> ListStruct
> SomeService
> etc

Indeed, it could be a time saver for users so they won't have to care about defining a prefix/suffix. Nevertheless, as it is implemented (prefix), suffix could be implemented pretty easily to let users make their choice. By default, it could be:
- *Array
- *Enum
- *Service
- *Struct

In addition, it would require to name the ```{Prefix}ClassMap{Suffix}``` class only ```ClassMap``` and its static method ```classMap``` would be named ```get``` for example (in order to avoid this issue: https://github.com/WsdlToPhp/PackageGenerator/issues/11 ).

I'm just worried for Structs that do already finish with the appended type. I could test the presence of the type in order to avoid appending it but it could be frustrating not having an harmony among the same type of structs that would always be appended with the type, I don't know ...

In any case, your suggestion is a good one for me
