### ISSUE TITLE
The tutorial.php does not show how to pass an object parameter in a method

### ISSUE THREAD

**Issue by tinonetic** [WsdlToPhp/PackageGenerator#130]
Hi,

I have successfully generated something but your documentation or the generated "tutorial.php" does not show any example of how to then pass the parameters expected in a method.

All it shows is something like this:

> 
> /**
>  * Samples for Cancel ServiceType
>  */
> $cancel = new \ServiceType\Cancel($options);
> /**
>  * Sample call for CancelOrder operation/method
>  */
> if ($cancel ->ProcessPayment(new \StructType\Cancel()) !== false) { //<--- the method expects parameters, how do I pass them?
>     print_r($cancel ->getResult());
> } else {
>     print_r($cancel ->getLastError());
> }

How do I pass parameters?

**Comment by mikaelcom** [comment]
Did you search for the class `\StructType\Cancel()` ? If you have a decent IDE, it should allow you to go into the class.

**Comment by mikaelcom** [comment]
The tutorial is just boilerplate. If it has to provide the parameter, it can then generate a really big file due to deep-nested parameters. It's not the goal to provide the parameters to the deepest level.
