### ISSUE TITLE
Float value gets converted to scientific notation and truncated

### ISSUE THREAD

**Issue by Natrak** [WsdlToPhp/PackageGenerator#131]
While testing this package with some WDSL that I have to use on a project I ran into an issue with large default values for decimal (float) values on a Struct.

- default: -79228162514264337593543950335
- maxOccurs: 1
- minOccurs: 0
- type: decimal

The number gets converted in the function definition to -7.922816251426434E+ instead of the correct value of -7.9228162514264E+28.

This results in "PHP Parse error:  syntax error, unexpected 'E' (T_STRING), expecting ')'". This could be OS specific or depending on compile options. I was running on PHP 7.2.3 (cli) (built: Feb 28 2018 05:48:02) ( NTS MSVC15 (Visual C++ 2017) x64 ).

Easy to wokr around with a command post generation to search replace these weird values with another default.

**Comment by mikaelcom** [comment]
> Easy to wokr around with a command post generation to search replace these weird values with another default.

Go ahead, make a pull request 😉  or guide me on what needs to be done,

Thx for the notice by the way!

**Comment by mikaelcom** [comment]
Great, thanks for your investigation!

This means the PhpGenerator project has to be improved as it is a limitation.

**Comment by mikaelcom** [comment]
see https://github.com/WsdlToPhp/PhpGenerator/issues/9#issuecomment-450566596
