### ISSUE TITLE
How to call classmap function for login in lumen?

### ISSUE THREAD

**Issue by anand007pandey** [WsdlToPhp/PackageGenerator#136]
This is my class file and i use like this way. I look at the tutorial.php and there is given the class Classmap where all the methods are given, which is bridge between WSDL and generate structs. But how to call them in our function and how to send parameter on functions. If possible give the example of one of them like for login i need to send partner key and environment code. 

use App\Interfaces\APIInterface;
use App\Exceptions\NotImplementedException;
use Comfisoft\MSA\JsonResponse;
use Comfisoft\imuissdk;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Crypt;
//use WsdlToPhp;
use \WsdlToPhp\PackageBase\AbstractStructBase;

class ImuisAPI implements APIInterface 
{
   public function login(\Illuminate\Http\Request $request) {
        try
        {
            $aPartnerkey     = $request->input('Partnerkey');
            $aOmgevingscode = $request->input('Environmentcode');
            $options = array(
                \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://cloudswitch.imuisonline.com/ws1_xml.asmx?wsdl',
                \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => \mydemo\imuissdk\ClassMap::get(),
            );
            $login = new \ServiceType\Login($options);
            //print_r($login);die;
            if ($login->Login(new \StructType\Login())!== false) {
                print_r($login->getResult());
            } else {
                print_r($login->getLastError());
            }
            //print_r($login);
        }
        catch(SoapFault $e)
        {
            $jsonResponse = empty($e->getMessage()) ? JsonResponse::error(class_basename($e)) : JsonResponse::error($e->getMessage());
        }
        //return $jsonResponse;
    }
}

This below file is Classmap.php
<?php
namespace mydemo\imuissdk;
/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'Login' => '\\StructType\\Login',
            'LoginResponse' => '\\StructType\\LoginResponse',
            'GetiMUISVersion' => '\\StructType\\GetiMUISVersion',
            'GetiMUISVersionResponse' => '\\StructType\\GetiMUISVersionResponse',
            'KeepSession' => '\\StructType\\KeepSession',
            'KeepSessionResponse' => '\\StructType\\KeepSessionResponse',
            'Logout' => '\\StructType\\Logout',
            'LogoutResponse' => '\\StructType\\LogoutResponse',
            'GetStamtabelRecords' => '\\StructType\\GetStamtabelRecords',
            'GetStamtabelRecordsResponse' => '\\StructType\\GetStamtabelRecordsResponse',
            'GetAdmInfo' => '\\StructType\\GetAdmInfo',
            'GetAdmInfoResponse' => '\\StructType\\GetAdmInfoResponse',
            'CreateJournaalpost' => '\\StructType\\CreateJournaalpost',
            'ArrayOfString' => '\\ArrayType\\ArrayOfString',
            'CreateJournaalpostResponse' => '\\StructType\\CreateJournaalpostResponse',
            'CreateStamTabelRecord' => '\\StructType\\CreateStamTabelRecord',
            'CreateStamTabelRecordResponse' => '\\StructType\\CreateStamTabelRecordResponse',
            'UpdateJournaalpost' => '\\StructType\\UpdateJournaalpost',
            'UpdateJournaalpostResponse' => '\\StructType\\UpdateJournaalpostResponse',
            'DeleteJournaalpost' => '\\StructType\\DeleteJournaalpost',
            'DeleteJournaalpostResponse' => '\\StructType\\DeleteJournaalpostResponse',
            'UpdateStamtabelRecord' => '\\StructType\\UpdateStamtabelRecord',
            'UpdateStamtabelRecordResponse' => '\\StructType\\UpdateStamtabelRecordResponse',
            'DeleteStamtabelRecord' => '\\StructType\\DeleteStamtabelRecord',
            'DeleteStamtabelRecordResponse' => '\\StructType\\DeleteStamtabelRecordResponse',
            'CheckConnection' => '\\StructType\\CheckConnection',
            'CheckConnectionResponse' => '\\StructType\\CheckConnectionResponse',
            'CreateVerkoopOrder' => '\\StructType\\CreateVerkoopOrder',
            'CreateVerkoopOrderResponse' => '\\StructType\\CreateVerkoopOrderResponse',
            'CreateInkoopOrder' => '\\StructType\\CreateInkoopOrder',
            'CreateInkoopOrderResponse' => '\\StructType\\CreateInkoopOrderResponse',
            'CreateGoederenontvangst' => '\\StructType\\CreateGoederenontvangst',
            'CreateGoederenontvangstResponse' => '\\StructType\\CreateGoederenontvangstResponse',
            'GetTimeStamp' => '\\StructType\\GetTimeStamp',
            'GetTimeStampResponse' => '\\StructType\\GetTimeStampResponse',
            'CreateInkoopfactuur' => '\\StructType\\CreateInkoopfactuur',
            'CreateInkoopfactuurResponse' => '\\StructType\\CreateInkoopfactuurResponse',
            'DeleteVerkooporder' => '\\StructType\\DeleteVerkooporder',
            'DeleteVerkooporderResponse' => '\\StructType\\DeleteVerkooporderResponse',
            'DeleteInkooporder' => '\\StructType\\DeleteInkooporder',
            'DeleteInkooporderResponse' => '\\StructType\\DeleteInkooporderResponse',
            'CreateVerkooporderRegel' => '\\StructType\\CreateVerkooporderRegel',
            'CreateVerkooporderRegelResponse' => '\\StructType\\CreateVerkooporderRegelResponse',
            'CreateInkooporderRegel' => '\\StructType\\CreateInkooporderRegel',
            'CreateInkooporderRegelResponse' => '\\StructType\\CreateInkooporderRegelResponse',
            'UpdateVerkooporderRegel' => '\\StructType\\UpdateVerkooporderRegel',
            'UpdateVerkooporderRegelResponse' => '\\StructType\\UpdateVerkooporderRegelResponse',
            'UpdateInkooporderRegel' => '\\StructType\\UpdateInkooporderRegel',
            'UpdateInkooporderRegelResponse' => '\\StructType\\UpdateInkooporderRegelResponse',
            'CreateVerkooporderPickbon' => '\\StructType\\CreateVerkooporderPickbon',
            'CreateVerkooporderPickbonResponse' => '\\StructType\\CreateVerkooporderPickbonResponse',
            'UpdateVerkooporderPickBonGepakt' => '\\StructType\\UpdateVerkooporderPickBonGepakt',
            'UpdateVerkooporderPickBonGepaktResponse' => '\\StructType\\UpdateVerkooporderPickBonGepaktResponse',
            'UpdateVerkooporderPickbonGereed' => '\\StructType\\UpdateVerkooporderPickbonGereed',
            'UpdateVerkooporderPickbonGereedResponse' => '\\StructType\\UpdateVerkooporderPickbonGereedResponse',
            'DeleteVerkooporderRegel' => '\\StructType\\DeleteVerkooporderRegel',
            'DeleteVerkooporderRegelResponse' => '\\StructType\\DeleteVerkooporderRegelResponse',
            'DeleteInkooporderRegel' => '\\StructType\\DeleteInkooporderRegel',
            'DeleteInkooporderRegelResponse' => '\\StructType\\DeleteInkooporderRegelResponse',
            'CreateVerkoopContract' => '\\StructType\\CreateVerkoopContract',
            'CreateVerkoopContractResponse' => '\\StructType\\CreateVerkoopContractResponse',
            'DeleteVerkoopContract' => '\\StructType\\DeleteVerkoopContract',
            'DeleteVerkoopContractResponse' => '\\StructType\\DeleteVerkoopContractResponse',
            'CreateVerkoopContractRegel' => '\\StructType\\CreateVerkoopContractRegel',
        );
    }
}
?>

**Comment by mikaelcom** [comment]
You do not have to call the ClassMap function as there is none, instead you have to look to the `new \StructType\Login()` parameter in order to be able to log in your Web Service.

The generated package works similarly to the native [SoapClient](http://php.net/manual/en/class.soapclient.php) class so please take a look to it first too.
