### ISSUE TITLE
SOAP Action in message

### ISSUE THREAD

**Issue by Ghanem-A** [WsdlToPhp/PackageGenerator#137]
Hey,

I've been having an issue with a SOAP Api I'm trying to consume using your library.

WSDL: http://www.tboholidays.com/HotelAPI_V7/HotelService.svc?singleWsdl (Hotel booking service).

Whenever I send any request I get the following error: The SOAP action specified on the message, '', does not match the HTTP SOAP Action, 'http://TekTravel/HotelBookingApi/CountryList'

Any help would be appreciated.

**Comment by mikaelcom** [comment]
I don't know if it would work but you could try calling the Service instance setHttpheader method in order to set the SOAPAction which is normally in the request HTTP headers.

**Comment by Ghanem-A** [comment]
@mikaelcom That's what I did and it worked, apologies for not posting the solution and closing the issue earlier, much thanks for your help.
