### ISSUE TITLE
How should I test newly generated Client?

### ISSUE THREAD

**Issue by NavyCoat** [WsdlToPhp/PackageGenerator#138]
How should I test newly generated Client? Should I mock SoapClient and overwrite default by `setSoapClient()` Method?

Or there are any other (better?) approaches?

**Comment by mikaelcom** [comment]
What's your goal exactly? Do you intend to test the generated code or the server responses?

**Comment by NavyCoat** [comment]
@mikaelcom I want to mock server responses. How my system will reacts on each.

**Comment by mikaelcom** [comment]
Then you have to take example on what has been done in the [PackageEws365](https://github.com/WsdlToPhp/PackageEws365) project meaning that:
- you have to use your own [SoapClientBase](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClientBase.php) by passing yours as the [--soap-client](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#soapclient) option
- you have to create your own [SoapClient](https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php)
- override what you want into the created SoapClient class

**Comment by NavyCoat** [comment]
Nice, thanks!

**Comment by 4n70w4** [comment]
Currently for 3.2.7 version need use `--soapclient` instead `--soap-client`.
