### ISSUE TITLE
How to use another xsd_types.yml

### ISSUE THREAD

**Issue by waldo2188** [WsdlToPhp/PackageGenerator#139]
I need to change the mapping of xsd_types.yml. I want to define `DateTime` as `DateTime` and not as `string`.

So, how with the CLI Tools can I set a different mapping ?
Is there an option to link to another xsd_types.yml ?

**Comment by mikaelcom** [comment]
Hi,
It is not currently implemented.

This is feasible as it would required to:

1. Add an option to take into account the mapping file (as the [Generator Options](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#generation-options))
2. Use this option value where it is used at lines [479](https://github.com/WsdlToPhp/PackageGenerator/blob/dd2dcf3910ec99c288181f8ca66b9a9a2ed29e48/src/File/AbstractModelFile.php#L479) and [493](https://github.com/WsdlToPhp/PackageGenerator/blob/dd2dcf3910ec99c288181f8ca66b9a9a2ed29e48/src/File/AbstractModelFile.php#L493) in the [AbstractModelFile](https://github.com/WsdlToPhp/PackageGenerator/blob/dd2dcf3910ec99c288181f8ca66b9a9a2ed29e48/src/File/AbstractModelFile.php) class.

Ready for a pull request? 😃

**Comment by waldo2188** [comment]
Hum, my php skills are a little rusty, but I can try;)

**Comment by waldo2188** [comment]
Thank you for your clarification.
My main goal was annotations, so the type hint can wait.

**Comment by mikaelcom** [comment]
[merged](https://github.com/WsdlToPhp/PackageGenerator/commit/bacd9d99cfb546e09eea46aec0593fb0435b27f1), [released](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/3.0.3) and [documented](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#xsd-types-mapping) :)

**Comment by mikaelcom** [comment]
just so you know https://github.com/WsdlToPhp/PackageGenerator/commit/37b1eee22a7d8f490cbdb0a83aefc190e3f69a01 ;)
