### ISSUE TITLE
Validations in wrong order

### ISSUE THREAD

**Issue by ragol** [WsdlToPhp/PackageGenerator#153]
I have a WSDL with the following definition:

```
<xs:element name="Region" minOccurs="0" maxOccurs="1" type="st:String50"/>
```

Type defintion is:
```
<xs:simpleType name="String50">
    <xs:restriction base="xs:string">
        <xs:maxLength value="50"/>
    </xs:restriction>
</xs:simpleType>
```

The generated PHP code is as follows:
```
    public function setRegion($region = null)
    {
        // validation for constraint: maxLength
        if ((is_scalar($region) && strlen($region) > 50) || (is_array($region) && count($region) > 50)) {
            throw new \InvalidArgumentException(sprintf('Invalid length, please provide an array with 50 element(s) or a scalar of 50 character(s) at most, "%d" length given', is_scalar($region) ? strlen($region) : count($region)), __LINE__);
        }
        // validation for constraint: string
        if (!is_null($region) && !is_string($region)) {
            throw new \InvalidArgumentException(sprintf('Invalid value, please provide a string, "%s" given', gettype($region)), __LINE__);
        }
        $this->Region = $region;
        return $this;
    }
``` 

It makes much more sense to check if `$region` is a string before checking the restrictions.

I noticed this on many different type definitions with restrictions. For example if a string field has a restriction checked by a regular expression the argument of the function matches the regular expression before checking that it is indeed a string. That doesn't make any sense.

So the general rule should be to check the most generic data type first and check restrictions later if they are applicable.

**Comment by mikaelcom** [comment]
There is currently no prioritization among rules. It's mainly [in the order of the restrictions](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/File/Validation/Rules.php#L73) declared/discovered for the attribute.

So it would require to define the rules priorities among the rules then each rule would be added to the setter in a better order.

In addition to this enhancement, it would be good to know from the exception message which attribute from which class is wrong.

**Comment by ragol** [comment]
Those rules are ok in any order, I suppose. What I was writing about happens in the caller: in [\WsdlToPhp\PackageGenerator\File\Validation\Rules::applyRules()](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/File/Validation/Rules.php#L38-L50).

The call to `applyRulesFromModel()` generates restriction checks. The following `if` checks the types. These two must be reversed, i.e. first check the type using the if-block and then call `applyRulesFromModel()`. You have to check if you have a string _before_ you check its length, match a regex pattern or whatever. The same applies to other types.

**Comment by mikaelcom** [comment]
@ragol is it possible for you test the [feature/issue-153](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-153) branch on your side in order to confirm that the validation rules are in a better order?
Thx

**Comment by ragol** [comment]
@mikaelcom  Looks good. :+1:
