### ISSUE TITLE
Is PackageGenerator's SOAP client asynchronous?

### ISSUE THREAD

**Issue by PhilMcLachlan** [WsdlToPhp/PackageGenerator#155]
If I make an API call to a WSDL generated class, will it be asynchronous?  Will it wait until the server responds, before I can make another request?

**Comment by mikaelcom** [comment]
Currently not. It uses the native SoapClient class from the [AbstractSoapClientBase](https://github.com/WsdlToPhp/PackageBase/blob/develop/src/AbstractSoapClientBase.php) class instanciated [here](https://github.com/WsdlToPhp/PackageBase/blob/develop/src/AbstractSoapClientBase.php#L78).

You can use your own SoapClient class using the approach demonstrated at the [PackageEws365](https://github.com/WsdlToPhp/PackageEws365) project.

But as illustrated in the [generated methods](https://github.com/WsdlToPhp/PackageEws365/blob/develop/src/ServiceType/EwsAdd.php#L68-L77), "alias" of the Soap operations, the asynchronous approach is currently not possible I think.

Let me know more about your needs.
