### ISSUE TITLE
Variable Already defined error

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#156]
I'm using 2.9.4

I’m trying to run the wsdl generation tool against a particular few wsdls and I’m getting a strange error.  Any way you might be able to shed some light on this.  This is the command I'm trying to 

```
C:\WsdlToPhp2>c:\php_7.1\php.exe ./wsdltophp.phar generate:package
--urlorpath="http://website:8113/change/xverification?wsdl" --destination="C:\serverpath\misc_wsdls\2018.00"  --composer-name="myproject/mypackage" --namespace="Verify" --composer-settings="config.disable-tls:true" --validation=false --force 
```

Here is the output:

```
Start at 2018-11-01 22:22:28
PHP Fatal error:  SOAP-ERROR: Parsing Schema: attribute 'http://www.change.generated.domain.com/v1/common/dto/common:ProcessorUser' already defined in 
phar://C:/serverpath/WsdlToPhp2/wsdltophp.phar/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 81
PHP Fatal error:  SOAP-ERROR: Parsing Schema: attribute 'http://www.change.generated.domain.com/v1/common/dto/common:ProcessorUser' already defined in 
phar://C:/serverpath/WsdlToPhp2/wsdltophp.phar/vendor/wsdltophp/packagebase/src/AbstractSoapClientBase.php on line 81

In GeneratorSoapClient.php line 33:

  Unable to load WSDL at "http://domain:8113/change/xverification?wsdl"!


In AbstractSoapClientBase.php line 81:

  SOAP-ERROR: Parsing Schema: attribute 'http://www.change.generated.domain.com/v1/common/dto/common:ProcessorUser' already defined
```

Any clue as to what is causing this issue? 

Thanks!

**Comment by mikaelcom** [comment]
Having the WSDL would be easier to be able to debug this but I currently think that this is due to the WSDL that is not well formated (as you certrainly suspected).

Otherwise, it is a feature that is not handled correctly by the native PHP SoapClient class for which I can't really help.

My advice would be to download the WSDL locally, then remove the duplicated attribute in order to try to generate the package with the fix.

Let me know then,

**Comment by faithfulman18** [comment]
I did just that late last night and finally got them to generate.

What's weird is the SOAPUI tool was able to open them up successfully but PHP barfs completely.  I assume that SOAPUI is allowing the WSDL to have a few nuances and still be ok.  Frustrating though.

After regenerating the files, things seem a bit broken for the code we have in place, so I'm working on it today and making sure it's not something else related to this.   I'll report back once I know more.

**Comment by faithfulman18** [comment]
Hmmm.... Well, although I was able to download the WSDL and make the correction that fixed the issue so the tool would work.  Now each time I setup a soap connections using:

      $get = new \Account\ServiceType\Get($options);
      $create = new \Account\ServiceType\Create($options);

Each of these seems to be taking 3.5 seconds to load and it's the same URL path.  

I'm certain it didn't take that long before.  Does it no longer cache the WSDL ?  Or do you think something else might be going on?

**Comment by faithfulman18** [comment]
Strangely, I copied and pasted the old set of WSDLS to php classes from a backup before I generated new files yesterday (as these services got an upgrade from the vendor), and they work very fast again for the services that were unaffected by the original problem above, while of course missing new methods.  Is there something that needs to be configured in a newer version of your tool that could be preventing the soap client from using a wsdl cache?  That's pretty much what it feels like is happening (and I see the cache being created regardless, but it seems like it's not actually using it), or  can you think of any other thing that could make a new version be so much slower.

**Comment by mikaelcom** [comment]
It depends on the schemas associated to the WSDL if there is any and if the network is easily reachable. There is not difference concerning the SoapClient usage except that the WSDL_CACHE is working well since versions [2.0.1](https://github.com/WsdlToPhp/PackageBase/tree/2.0.1) and [1.0.12](https://github.com/WsdlToPhp/PackageBase/tree/1.0.12) of PackageBase project.

**Comment by faithfulman18** [comment]
What is odd is that the last time I went to build new wsdls, we fixed an issue and I ran the wsdls with version 2.5.0.

The latest version seems to be doing something different.

Do you have the WSDL_CACHE as a setting that I should be setting somewhere, or is it defaulted on?

**Comment by mikaelcom** [comment]
It uses the default settings from the [AbstractSoapClientBase.php Line 132 to Line 155](https://github.com/WsdlToPhp/PackageBase/blob/develop/src/AbstractSoapClientBase.php#L132-L155)

**Comment by faithfulman18** [comment]
Well, looks like in the past I never had to set the WSDL_CACHE in the options for this to work.  I must have generated this particular large webservice earlier than I thought, prior to you adding that option.

I found that you are manually setting it to 'not cache' as the default, so after setting it to WSDL_CACHE_BOTH on all of my SOAP calls, it is now responding fast again.  Thanks for pointing me to that code.  That was most helpful.

So, back to the original issue with the poorly modified schema ... while downloading the wsdl and manually tweaking the code in it and generating the WSDLtoPhp classes completed successfully, when I try to go to use the generated WSDLs now the only issue I'm having is that even though your tool is working, when PHP seems to still be trying to interface with the WSDL as it gets the same error your tool was giving me earlier.

```
SOAP-ERROR: Parsing Schema: attribute 'http://www.change.generated.domain.com/v1/common/dto/common:ProcessorUser' already defined...
```

Is there a way, to make PHP bypass the WSDL at the endpoint, and just use the classes method in the project and send and receive the SOAP message until I can convince the vendor to fix their schema?

**Comment by mikaelcom** [comment]
Try the non-WSDL mode maybe? If it can be done and works, let me know as I recently answered to another issue that it would not be possible :disappointed:

**Comment by faithfulman18** [comment]
From the php website, it looks like the non-wsdl mode requires you to set a location and a uri as optional parameters, and the wsdl parameter in the soapClient as a null.  But the current project doesn't allow for the uri to be set, but just the location.  I think that may be why it won't currently work.  Otherwise, maybe it could.

**Comment by faithfulman18** [comment]
Is that something you plan to add?

**Comment by mikaelcom** [comment]
I did not plan to add it no until you surfaced it. Can you then create the issue for the PackageBase proiject as it's not related to this project anymore?

Thx

**Comment by faithfulman18** [comment]
Can you point me to the PackageBase project ?  I'm not sure where that exists?

**Comment by mikaelcom** [comment]
This is https://github.com/WsdlToPhp/PackageBase

**Comment by mikaelcom** [comment]
Fixed with https://github.com/WsdlToPhp/PackageBase/issues/28
