### ISSUE TITLE
Missing entry from ClassMap

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#157]
Hello,

I noticed that from a previous generation of wsdl files to the latest version, I seem to be missing one entry from the classmap as well as no associated file for a class.  Because of the issue #156 I'd like to know where I would look at the WSDL file itself and the code that would decide what all needs to be created for the classes in this project.  

Strangely, when opening the WSDL in SoapUI, it generates a proper example, but the WSDL to PHP generation code no longer does.  The associated classes field use to generate this (and have an associated text.php file):

```
 /**
     * The Text
     * Meta informations extracted from the WSDL
     * - maxOccurs: 50
     * - minOccurs: 0
     * @var \Account\StructType\Text[]
     */
    public $Text;
    /**
```

However, running it now generates it as a plain string using the wsdl to php generation (which is incorrect and will error out when trying to make a soap call):

```
    /**
     * The Text
     * Meta informations extracted from the WSDL
     * - maxOccurs: 50
     * - minOccurs: 0
     * - maxLength: 40
     * @var string[]
     */
    public $Text;
    /**
```

SOAP UI generates an example for this method with the 'Text' property looking like this, which matched how the old generation of the code use to work:

```
               <!--0 to 50 repetitions:-->
               <Text>
                  <!--Optional:-->
                  <EntryId>?</EntryId>
                  <!--Optional:-->
                  <Text>?</Text>
               </Text>
               <!--Optional:-->
```

If you can please direct me at what I should be looking at on the WSDL and where in the code that would exist, I would greatly appreciate it.

Thanks,
Kevin

**Comment by mikaelcom** [comment]
Maybe you should make some tests modifying the code part from https://github.com/WsdlToPhp/PackageGenerator/commit/2853cda114d82993f97a2af9f5e6f1e41797f3e7?

**Comment by faithfulman18** [comment]
Is there something i could navigate to the WSDL endpoint and see that would be of some help in identifying why it's not generating correctly?

**Comment by faithfulman18** [comment]
I found this section in the WSDL.  I'm wondering if the fact that both the name attribute at the top and inner property being both named "Text" is throwing it off.  I'm thinking this is what is going on.  I'm not quite sure how it worked before though.  Did something in the project change to no longer allow this?

```
<xsd:element maxOccurs="50" minOccurs="0" name="Text">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element maxOccurs="1" minOccurs="0" name="EntryId">
        <xsd:simpleType>
          <xsd:restriction base="xsd:short" /> 
        </xsd:simpleType>
      </xsd:element>
      <xsd:element maxOccurs="1" minOccurs="0" name="Text">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
           <xsd:maxLength value="40" /> 
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>

```

Any thoughts?

**Comment by mikaelcom** [comment]
This is possibly the case but the second Text element is an attribute so it should not be considered as a Struct so it should not override the first Text type hint.

In addition, you should try each version from which it was working in order to target the version from which it started to work improperly, it could help targeting the modification that introduces this issue.

I won't be able to work on it before November 15th I'm sorry, so if you have time to dig in it, good luck.

**Comment by faithfulman18** [comment]
I've gone back until the very first version I ever used and still cannot get it to generate that class properly.  So I suppose that may mean either something has changed in the soap extension or the vendor made some small change that triggered the wsdltophp tool do it properly in the past and no longer now.  I'm not sure which.

I'd like to help diagnose this further, however I'm not sure how to get started.  I've only used the .phar files in the past and run this command line.  I've downloaded the 2.x project, but I don't see a way to trigger the process to run anywhere.  All I see are a bunch of files that are classes, extending classes, etc.

Any suggestion on how I can get started.  Do I need to do some process that wraps the source code back into a PHAR file, or can I make a change on the fly and run a test just directly with the source code?

**Comment by faithfulman18** [comment]
I did find this link:  https://github.com/WsdlToPhp/PackageGenerator/blob/2.x/CONTRIBUTING.md

I've never used composer before, but trying to get it setup I was able to download the dependencies, however when I try to run 'composer build' it seems to error out:  

```
c:\Git\PackageGenerator-2.x>composer build
> box build --verbose
'box' is not recognized as an internal or external command,
operable program or batch file.
Script box build --verbose handling the build event returned with error code 1
```

I must be missing a step?

**Comment by mikaelcom** [comment]
A class is generated as soon as a Struct is detected from the [__getTypes](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/SoapClient/Structs.php#L37) call.

So Struct classes come from the SoapClient class.

**Comment by faithfulman18** [comment]
Either its my lack of experience with Symfony or namespaces, but I was having trouble following how the process was working.  

The one thing I do know is that the struct is somehow being overwritten by the property directly within it with the same name.

**Comment by faithfulman18** [comment]
Is this something you might have a chance to get too soon?

**Comment by mikaelcom** [comment]
Can you provide me the WSDL that I'll keep privately needless to say to contact@wsdltophp.com?

Thx

**Comment by faithfulman18** [comment]
Sorry for the delay.  I've emailed you a stripped out version that I have tested against the script.  You may need to change the schema location pathing in the .wsdl file though, as I'm on a windows box.

**Comment by faithfulman18** [comment]
Will you let me know that you received it?

**Comment by mikaelcom** [comment]
I'm currently working on a customer website so I don't have much time nowadays. I indeed received your file. I'll get back to you as soon as possible, sorry...

**Comment by mikaelcom** [comment]
The issue here is that the call to __getTypes from the native PHP SoapClient class returns this:
```
[34] => short Text
[41] => string Text
[48] => struct Text {
    EntryId EntryId;
    Text Text;
}
[50] => string Text
```
So there is 4 identically-named elements but with 3 different types :fearful:.

In addition, the TagRestriction parser finds this:
```xml
<xsd:restriction base="xsd:string">
    <xsd:maxLength value="40"/>
</xsd:restriction>
```
which conducts to declare the inheritance of the first Text struct (actually not a Struct : "struct": false) correctly defined as:
```json
{
    "attributes": [
        {
            "containsElements": false,
            "removableFromRequest": false,
            "type": "EntryId",
            "inheritance": "",
            "abstract": false,
            "meta": [],
            "name": "EntryId",
            "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\StructAttribute"
        },
        {
            "containsElements": false,
            "removableFromRequest": false,
            "type": "Text",
            "inheritance": "",
            "abstract": false,
            "meta": [],
            "name": "Text",
            "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\StructAttribute"
        }
    ],
    "restriction": false,
    "struct": false,
    "types": [],
    "values": [],
    "inheritance": "",
    "abstract": false,
    "meta": [],
    "name": "Text",
    "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\Struct"
}
```
to this declaration:
```json
{
    "attributes": [
        {
            "containsElements": false,
            "removableFromRequest": false,
            "type": "EntryId",
            "inheritance": "",
            "abstract": false,
            "meta": {
                "maxOccurs": "1",
                "minOccurs": "0"
            },
            "name": "EntryId",
            "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\StructAttribute"
        },
        {
            "containsElements": false,
            "removableFromRequest": false,
            "type": "Text",
            "inheritance": "",
            "abstract": false,
            "meta": {
                "maxOccurs": "1",
                "minOccurs": "0"
            },
            "name": "Text",
            "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\StructAttribute"
        }
    ],
    "restriction": false,
    "struct": false,
    "types": [],
    "values": [],
    "inheritance": "string",
    "abstract": false,
    "meta": {
        "maxLength": "40"
    },
    "name": "Text",
    "__CLASS__": "WsdlToPhp\\PackageGenerator\\Model\\Struct"
}
```

I don't want to be rude but using 4 times the same with 3 different types does not seem very clean, just a personal opinion. As the structs from the __getTypes are parsed in the order returned by this method, this is the first that is taken into account in order to define the type of the named element. As the Text element is firstly defined as a *short* and not a struct, it's parsed as not a struct.

This situation is tricky as the native SoapClient detects things and parsing the WSDL leads to something else. As the native PHP SoapClient is then used to send the request, in some case, *overriding* the data passed to the called methods won't help as the native SoapClient won't accept it or will transform it a malformed XML request.

*Any chance that this Web Service would be refactored?*

**Comment by faithfulman18** [comment]
Unfortunately, it isn't likely to be changed, and the business producing the Web Service is large and this web service is extensive.  I can ask them, but even if they would agree to do it it wouldn't probably happen for quite some time.  What's strange is that this use to work with the PackageGenerator in the past.

But, I cannot seem to get an older version to work any longer.  So ... I'm wondering if they changed something that effected it.  

So, you are saying you are seeing 4 versions of the type "Text", however I'm not sure I follow that.  There is the parent Text and then there is the children "Text and EntityId". ... Where are you coming up with the other two?

Regardless, are you saying you don't think there is a solution to fix it within the project?  Or is it just a complex fix?

**Comment by mikaelcom** [comment]
> Unfortunately, it isn't likely to be changed, and the business producing the Web Service is large and this web service is extensive. I can ask them, but even if they would agree to do it it wouldn't probably happen for quite some time. What's strange is that this use to work with the PackageGenerator in the past.

It has been improved since the original project from https://github.com/mikaelcom/WsdlToPhp. And even from this project has been mainly improved. If you're sure the Web Service provider did not change the WSDL, using the older versions incrementally from version https://github.com/WsdlToPhp/PackageGenerator/releases/tag/0.0.1 should help targeting the introduction of this difference, but it's not easy I admit :wink:.

> So, you are saying you are seeing 4 versions of the type "Text", however I'm not sure I follow that. There is the parent Text and then there is the children "Text and EntityId". ... Where are you coming up with the other two?

Among the WSDL and XSD files, there is actually 5 declaration of the Text elements (2 are repeated) :
```xml
<xsd:element maxOccurs="50" minOccurs="0" name="Text">
    <xsd:simpleType>
        <xsd:restriction base="xsd:short"></xsd:restriction>
    </xsd:simpleType>
</xsd:element>
```
```xml

<xsd:element maxOccurs="50" minOccurs="0" name="Text">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element maxOccurs="1" minOccurs="0" name="EntryId">
				<xsd:simpleType>
					<xsd:restriction base="xsd:short">
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element maxOccurs="1" minOccurs="0" name="Text">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
```
```xml
<xsd:element maxOccurs="1" minOccurs="0" name="Text">
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:element>
```

> Regardless, are you saying you don't think there is a solution to fix it within the project? Or is it just a complex fix?

It's certainly a complex one as it would need to reconsider the SoapClient parsing and the XML files parsing, but certainly for a better result. It would need to have better defined Structs starting from the Structs parser parsing. Then the WSDL parses will need to look the Structs declaration more deeply in order to target the right one.

**Comment by mikaelcom** [comment]
> What are the chances that you'll be able to implement the necessary changes to fix the issue?

It's either I really find the right solution or I realize trying to fix it that it can't be fixed. Additionnally, I'm really busy on a customer project so it's not my priority right now. I could ask your deadline but I dare not to ask as I presume the answer :wink:.

What could help is that you :
- use the old code version in order to create what is missing
- fix the types of the attributes if necessary
- make it work by manually adding what is missing

When that's done, I could rely on it in order to be sure of what is expected :smiley:.

**Comment by faithfulman18** [comment]
> use the old code version in order to create what is missing
fix the types of the attributes if necessary
make it work by manually adding what is missing

So, to be sure, when you say "fix the types of attributes" or "make it work by manually adding what is missing" .. what do you mean?  Is there something I can manually tweak in the Web Service WSDL to fix the issue?  Or do you just mean try to get the vendor to change their web service so nothing has the same named struct?

Or Did you mean something else entirely?

**Comment by mikaelcom** [comment]
I mean fix the generated package in order so it reflects what should be generated in order to make it fully working ;)

**Comment by faithfulman18** [comment]
So, I think I understand what you are saying is happening above, but where each of the named 'Text' pieces are happening, it seems like the first instance is what is becoming that specific data type for all other instances.  Instead of  just living within the context of the overarching 'complexType' section.

Is that correct?

So, while I agree that is seems like a bad practice, specifically for a Text struct to have a property within it to also be named 'Text'.  I'm not quite sure why the Text short inside an adjacent complexType is having a negative impact on subsequent adjacent complexType's with all together different set of properties.

Shouldn't they be treated differently since one is an actual Struct and one is just a property and both are in different complextypes?  Or am I misunderstanding what you are saying?

(fyi: I contacted the vendor by the way, and they let me know this hasn't been a problem for other customers and asked me if there was an error from the PHP parser, which it sounds like isn't actually the issue, if I understand you correctly. )

**Comment by mikaelcom** [comment]
>So, I think I understand what you are saying is happening above, but where each of the named 'Text' pieces are happening, it seems like the first instance is what is becoming that specific data type for all other instances. Instead of just living within the context of the overarching 'complexType' section.
>
>Is that correct?

YES

>So, while I agree that is seems like a bad practice, specifically for a Text struct to have a property within it to also be named 'Text'. I'm not quite sure why the Text short inside an adjacent complexType is having a negative impact on subsequent adjacent complexType's with all together different set of properties.
>
>Shouldn't they be treated differently since one is an actual Struct and one is just a property and both are in different complextypes? Or am I misunderstanding what you are saying?

YES they should and it's the trickiest part

**Comment by faithfulman18** [comment]
Ah.  Any idea when you might have an opportunity to work on it?  You mentioned that you were busy with another project at the moment, so I just wanted to ask and see what your time frame might be.

Thanks,

Kevin

**Comment by mikaelcom** [comment]
To be honest, it would be at the end of this year. It seems to be something that is missing from this generator that was not detected before as the generated packages were functionnal for most of them. But it would be a great improvement!

**Comment by faithfulman18** [comment]
Alright.  I'll try to be patient.  I need to learn symfony so I can help.  

Let me know when you have something more on this.  Thanks @mikaelcom!

**Comment by mikaelcom** [comment]
You don't really need Symfony knowledge, at least Composer, Git and that's it ;)

**Comment by faithfulman18** [comment]
Well, I use git and php every day.  Just haven't gotten into any frameworks, so I haven't used composer.  I suppose I need to mainly get familiar with composer then.

**Comment by boryashkin** [comment]
It seems that i have a related issue:

```
	<xs:element name="City">
		<xs:annotation>
			<xs:documentation>City identifier</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="Location">
					<xs:attribute name="Code" type="typeIATACode" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="typeStructuredAddress">
		<xs:annotation>
			<xs:documentation>A fully structured address</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="City" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The city name for the requested address, e.g. Atlanta.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
	</xs:complexType>
```
This declaration leads to a wrong TypeStructuredAddress::__constructor(), which have the first City as a type hinted parameter, which is object, insted of the second City, which is string.

```
class TypeStructuredAddress extends AbstractStructBase
{
    public function __construct(\air45\StructType\City $city = null)
}
```

**Comment by faithfulman18** [comment]
Any progress on this ?

**Comment by mikaelcom** [comment]
Not yet, soon I hope

**Comment by mikaelcom** [comment]
@faithfulman18  Could you let me know how it goes using this branch ? I improved many things thanks to this issue

**Comment by faithfulman18** [comment]
I must be doing something wrong .... but I keep getting an error using the new files....

Here is my command
c:\Git\PackageGenerator-2.x>php console generate:package --urlorpath="http://site/service?wsdl" --destination="C:\Git\wsdltestoutput\test" --composer-name="myproject/mypackage" --namespace="service" --composer-settings="config.disable-tls:true" --validation=false --force

PHP Warning:  require_once(C:\Git\PackageGenerator-2.x/vendor/autoload.php): failed to open stream: No such file or directory in C:\Git\PackageGenerator-2.x\console on line 6

Warning: require_once(C:\Git\PackageGenerator-2.x/vendor/autoload.php): failed to open stream: No such file or directory in C:\Git\PackageGenerator-2.x\console on line 6
PHP Fatal error:  require_once(): Failed opening required 'C:\Git\PackageGenerator-2.x/vendor/autoload.php' (include_path='.;') in C:\Git\PackageGenerator-2.x\console on line 6

Fatal error: require_once(): Failed opening required 'C:\Git\PackageGenerator-2.x/vendor/autoload.php' (include_path='.;') in C:\Git\PackageGenerator-2.x\console on line 6

**Comment by faithfulman18** [comment]
Nevermind ... I forgot I needed to run the 'install composer' command

Okay, I just finished building a whole set of WSDL files successfully using this branch, and I have copied them out and tested them on the existing project I was working on that experienced this original issue and it is everything is working splendidly.  Thank you so much!  :)

When do you suppose you'll create a new build with a new PHAR file?

**Comment by mikaelcom** [comment]
Soon thanks to your quick testing :wink:

**Comment by faithfulman18** [comment]
Great.  Thanks! 👍
