### ISSUE TITLE
question - multiple ports with same service name

### ISSUE THREAD

**Issue by nsn0x01** [WsdlToPhp/PackageGenerator#160]
Hi,

I'm trying this tool with many complex wsdl files, I have an issue that honestly I don't know if it's a limitation of SoapClient or a bug on generated classes.

I have this wsdl where it was defined a same service name for multiple ports name.

part of wsdl:

  <service name="ExternalCacheAccessService">
        <port name="ExternalCacheAccessPort" binding="tns:ExternalCacheAccessBinding">
            <soap:address location="http://localhost:8080/trx/ExternalCacheAccessService" />
        </port>
    </service>
    <service name="SystemService">       
        <port name="SystemPingPort" binding="tns:SystemPingBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
        <port name="SystemInfoPort" binding="tns:SystemInfoBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
        <port name="SystemtimePort" binding="tns:SystemTimeBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
    </service>

generated code in the service class:

    /**
     * Method to call the operation originally named service
     * This method has been renamed because it is defined several times but with
     * different signature
     * @uses SoapClientSystemBase::getSoapClient()
     * @uses SoapClientSystemBase::setResult()
     * @uses SoapClientSystemBase::getResult()
     * @uses SoapClientSystemBase::saveLastError()
     * @param \TestClient\Services\System\StructType\PingReq $parameters
     * @return \TestClient\Services\System\StructType\PingRsp|bool
     */
    public function service_245c7036753daf3b829e971418dbcd33(\TestClient\Services\System\StructType\PingReq $parameters)
    {
        try {
            $this->setResult($this->getSoapClient()->service($parameters));
            return $this->getResult();
        } catch (\SoapFault $soapFault) {
            $this->saveLastError(__METHOD__, $soapFault);
            return false;
        }
    }

Every method in the generated file has same code, everything goes on method service and the object $parameters has the correct model / type. 
The break point is when the code is executed, the request for each method is always generated using the main service and so the client generate a wrong request using the model for ExternalCacheAccessService.

Any idea, suggests / workaround?

**Comment by mikaelcom** [comment]
If each port has its own location, you can already call the `setLocation` method on the Service instance passing through the SOAPAction location before calling the method.

In addition, if the `PingReq` is inherited from multiple classes, it would mean you have to use one of the inherited classes in order to send the right request content.

Let me know if I'm missing something or if I can help.

**Comment by nsn0x01** [comment]
Hi,

thanks for your reply...

sorry I did not include the part of the wsdl:

    <binding name="SystemInfoBinding" type="tns:SystemInfoPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="service">
            <soap:operation soapAction="http://localhost:8080/kestrel/SystemService"/>
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="ErrorInfoMsg">
                <soap:fault name="ErrorInfoMsg" use="literal" />
            </fault>
        </operation>
    </binding>
<binding name="ExternalCacheAccessBinding" type="tns:ExternalCacheAccessPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="service">
            <soap:operation soapAction="http://localhost:8080/kestrel/ExternalCacheAccessService"/>
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="ErrorInfoMsg">
                <soap:fault name="ErrorInfoMsg" use="literal" />
            </fault>
        </operation>
    </binding>

  <service name="ExternalCacheAccessService">
        <port name="ExternalCacheAccessPort" binding="tns:ExternalCacheAccessBinding">
            <soap:address location="http://localhost:8080/trx/ExternalCacheAccessService" />
        </port>
    </service>
    <service name="SystemService">       
        <port name="SystemPingPort" binding="tns:SystemPingBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
        <port name="SystemInfoPort" binding="tns:SystemInfoBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
        <port name="SystemtimePort" binding="tns:SystemTimeBinding">
            <soap:address
                    location="http://localhost:8080/trx/SystemService" />
        </port>
    </service>

Unfortunately the location is always the same for "SystemService".. SoapClient try lookup the service and get always the first match.. so the request is generated always for "tns:ExternalCacheAccessBinding"...

I guess only solution is split the wsdl files into multiple single services... do you have any suggests?

**Comment by mikaelcom** [comment]
I have an idea but to be sure, I would need some clarification of what you actually send (PHP classes used, sent XML request) and what you actually need to send (XML request).

**Comment by nsn0x01** [comment]
POST https://endpoint/SystemService HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "http://localhost:8080/kestrel/SystemService"
Content-Length: 453
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

all requests are as the previous one, endpoint and action are the same for all ports, only the XML request it's different (a model request for each binding).

Splitting the bindings in the single wsdl works well, I wrote a tool for that, It's a limitation of SoapClient that match the first service and port in the wsdl.

**Comment by mikaelcom** [comment]
So you found a workaround, right?

Did you use the SoapClient inheritance as well? As demonstrated for example in the [PackageEws365](https://github.com/WsdlToPhp/PackageEws365) package?

**Comment by nsn0x01** [comment]
Yes I found the workaround splitting the wsdl in multiple wsdl files, so the mapping is one to one. I guess there is no other way.

Yes I'm using the inheritance but unfortunately I can't set extra information into array $options to my SoapClient because the abstract class (AbstractSoapClientBase) is removing keys not present in your wsdl default options. 
So I added setter method for injecting extra data, a logger and other stuff.

**Comment by mikaelcom** [comment]
Great to hear!

**Comment by mikaelcom** [comment]
> Yes I'm using the inheritance but unfortunately I can't set extra information into array $options to my SoapClient because the abstract class (AbstractSoapClientBase) is removing keys not present in your wsdl default options.
> So I added setter method for injecting extra data, a logger and other stuff.

Did you try overridding the [AbstractSoapClientBase::getDefaultWsdlOptions()](https://github.com/WsdlToPhp/PackageBase/blob/develop/src/AbstractSoapClientBase.php#L129-L157) method called at https://github.com/WsdlToPhp/PackageBase/blob/develop/src/AbstractSoapClientBase.php#L66 when overridding the SoapClientBase in order to add your own keys?

**Comment by nsn0x01** [comment]
I missed that method, should help in my case but injection is not bad at all :)
Thanks!
