### ISSUE TITLE
Programming Editor

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#169]
Is there a good way to make a programming editor to auto-complete with the folder structure that is generated from this project?  

I was hoping to be able to use something like a VS Code and be able to enter in an object and have the autocomplete functionality of the generated classes show me what all I need to add without having to open up each and every class file name to see what is required.

Or maybe there are some other tools that these files work particularly well with?

Thanks!

**Comment by mikaelcom** [comment]
What are you using currently?

PHP is best with [PhpStorm](https://www.jetbrains.com/phpstorm/) or [Eclipse PDT](https://www.eclipse.org/pdt/). Both IDE provides auto-completion, that's one of the main foals of generating the PHP SDK from a WSDL.

**Comment by faithfulman18** [comment]
I'm using Visual Studio Code.

How do the two editors you mentioned above make use of the Auto-Completion.  Do you have to point a setting to the folder, or does it just search throughout the folder that is apart of the project already?

**Comment by mikaelcom** [comment]
You just open your project folder, they are adapted for PHP so they know what they have to do and what they have to provide :wink:

**Comment by faithfulman18** [comment]
Alright, thanks.
