### ISSUE TITLE
Create PHAR

### ISSUE THREAD

**Issue by sagikazarmark** [WsdlToPhp/PackageGenerator#17]
It would be great if people could just use a phar for generating classes.

**Comment by ceeram** [comment]
I can do that if desired
Op 11 aug. 2015 19:53 schreef "Márk Sági-Kazár" <notifications@github.com>:

**Comment by sagikazarmark** [comment]
:+1:

**Comment by mikaelcom** [comment]
:+1: , go ahead @ceeram if you really wish, don't forget to add you as a Contributor in the composer.json file

**Comment by ceeram** [comment]
Will do when i get home
Op 11 aug. 2015 22:42 schreef "Mikaël DELSOL" <notifications@github.com>:

**Comment by mikaelcom** [comment]
Take your time :wink: , as I did not create any phar until now, please make a pull request as complete as possible so I can understand how to handle it myself if I need to do it later, thks

**Comment by sagikazarmark** [comment]
@mikaelcom it is simple:

The most common way is using [box](http://box-project.org/).

1. Download the box.phar
2. Create a box.json like this:

``` json
{
    "chmod": "0755",
    "directories": [
        "src"
    ],
    "finder": [
        {
            "name": "*.php",
            "exclude": [
                "Tests",
                "tests",
                "test",
                "Test",
                "build",
                "spec",
                "bin"
            ],
            "in": "vendor"
        }
    ],
    "git-version": "package_version",
    "main": "console",
    "output": "console.phar",
    "stub": true
}
```
3. Run `box.phar build`

Short tutorial. ;)

**Comment by mikaelcom** [comment]
Ok, thks, if @ceeram wants to do it, well I let him do it, otherwise I'll take care of it in the next days, I can't say when :wink:

**Comment by sagikazarmark** [comment]
Sure thing, I just outlined how it works.

**Comment by ceeram** [comment]
That indeed is roughly how it works, its fairly easy.

Here is a nice write up about creating phars, and even shows how easy you
can add a self-update command to your application.
I will send a PR with the changes needed to build a phar, do you want a
generated phar included in the PR, or will you run box build yourself?


2015-08-11 23:40 GMT+02:00 Márk Sági-Kazár <notifications@github.com>:

**Comment by ceeram** [comment]
Oops forgot to include the link: http://moquet.net/blog/distributing-php-cli/

**Comment by ceeram** [comment]
One note: if you want to generate the phar yourself, make sure you first run `composer install --no-dev` else the phar will contain the dev dependencies which will bloat the phar and increase the build time.

**Comment by mikaelcom** [comment]
@ceeram: I could totally let you take care of the phar generation regarding your todo list and my comment included in your PR, let me know if you can

**Comment by ceeram** [comment]
Will get back with more verbose reply to this tomorrow i hope. No time
today.
Op 12 aug. 2015 13:10 schreef "Mikaël DELSOL" <notifications@github.com>:

**Comment by mikaelcom** [comment]
I made a new branch for the phar creation from the mandevilla one : [mandevilla-phar](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/mandevilla-phar). Box is indeed pretty easy to use. (Sorry @ceeram I copied a bit your PR #19)

My last concern is to clarify the usage of the phar and the way to download it in the readme as you mentionned ```Update readme before merging``` in the PR #19

**Comment by sagikazarmark** [comment]
I guess @ceeram meant update the console examples to use the phar.

**Comment by mikaelcom** [comment]
I updated the readme file by replacing the usage of the console by the phar file on the [mandevilla-phar](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/mandevilla-phar) branch

**Comment by mikaelcom** [comment]
phar file is now ```createable```, included in the ```bin``` folder, attached to the Github release and finally downloadable at http://phar.wsdltophp/wsdltophp.phar.

It can be enhanced/improved form now on.
