### ISSUE TITLE
Int setter throws exception when setting null

### ISSUE THREAD

**Issue by lessmind** [WsdlToPhp/PackageGenerator#178]
Hi, it's me again.

Full schema available in 
https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Universal_API_Schemas_and_WSDLs.htm%3FTocPath%3DGetting%2520Started%7CGetting%2520Connected%7C_____2

Schema Version: Current 18.4

After upgrade to 3.1.0, the `NumberInParty` attributes from Air.xsd went wrong.
```xml
<xs:attribute name="NumberInParty">
	<xs:annotation>
		<xs:documentation>Number of person traveling in this air segment excluding the number of infants on lap.</xs:documentation>
	</xs:annotation>
	<xs:simpleType>
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
```

Now produces this, which `null` will always failed at `$numberInParty < 1 `
```php
public function setNumberInParty($numberInParty = null)
{
    // validation for constraint: int
    if (!is_null($numberInParty) && !is_numeric($numberInParty)) {
        throw new \InvalidArgumentException(sprintf('Invalid value %s, please provide a numeric value, %s given', var_export($numberInParty, true), gettype($numberInParty)), __LINE__);
    }
    // validation for constraint: maxInclusive
    if ($numberInParty > 99) {
        throw new \InvalidArgumentException(sprintf('Invalid value %s, the value must be inferior or equal to 99, %s given', var_export($numberInParty, true), $numberInParty), __LINE__);
    }
    // validation for constraint: minInclusive
    if ($numberInParty < 1) {
        throw new \InvalidArgumentException(sprintf('Invalid value %s, the value must be superior or equal to 1, %s given', var_export($numberInParty, true), $numberInParty), __LINE__);
    }
    $this->NumberInParty = $numberInParty;
    return $this;
}
```

Thanks.

**Comment by mikaelcom** [comment]
Hello again, who is this responsible for this sh*t? Oh this is me !
If you don't want to waste time with validation while it is fixed, you can disable it passing to the [validation option](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#validation) `false`.

**Comment by lessmind** [comment]
Thanks for your help ! I'll try it now.

And don't be upset, we all been there too :)

**Comment by mikaelcom** [comment]
@lessmind It should be fixed with the develop branch. Can you try before I release it with a bunch of fixes?
Thanks

**Comment by lessmind** [comment]
Oh sorry I'm in Lunar New Year vacation now, I won't access the code until 2/11.
