### ISSUE TITLE
undefined StructType class

### ISSUE THREAD

**Issue by tbl0605** [WsdlToPhp/PackageGenerator#185]
Hi,
when we generate php classes for our "roc.wsdl" web service, we end up with a method 
```\ServiceType\Operation::setSoapHeaderMessage(\StructType\Max2048TextType $message, $nameSpace = 'urn:amc:ci', $mustUnderstand = false, $actor = null)``` that uses an unknown \StructType\Max2048TextType type for its "$message" parameter.

All our .xsd and .wsdl files can be found at: https://drive.google.com/drive/folders/1m-OK8vhcMVsWKa_pyyesQK81rtTyc-PV

Note that after retrieving these .xsd and .wsdl files, you must first replace all "\_\_LOCAL_PATH\_\_" occurrences by the new local path of those files.

Thank you for your help :)
Thierry.

**Comment by mikaelcom** [comment]
Is it possible for you to use the [feature/issue-185](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-185) branch with:
```bash
php /var/www/console g:p \
    --urlorpath=roc.wsdl \
    --destination=./ \
    --composer-name=roc/soap \
    --force
```
in order to validate the fix before merging it :)

Thanks

ps: import use relative path, you don't need the full path in your xsd, just put the file name if it is in the same directory as the WSDL

**Comment by tbl0605** [comment]
> 
> 
> Is it possible for you to use the [feature/issue-185](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-185) branch with:
> 
> ```shell
> php console g:p \
>     --urlorpath=roc.wsdl \
>     --destination=./ \
>     --composer-name=roc/soap \
>     --force
> ```
> 
> in order to validate the fix before merging it :)
> 
> Thanks
> 
> ps: import use relative path, you don't need the full path in your xsd, just put the file name if it is in the same directory as the WSDL

Hi @mikaelcom,
thank you very much, I confirm you that your patch is working great, the issue is fixed for me ;)

Thierry.
