### ISSUE TITLE
How generate package from cli if installed through composer?

### ISSUE THREAD

**Issue by 4n70w4** [WsdlToPhp/PackageGenerator#186]
I don't see wsdltophp command file. I do not understand how to run through the console.

**Comment by mikaelcom** [comment]
The binary file is not provided with composer.
What is the environment of your poject?
Concretely, you have to create a command that uses the [project way](https://github.com/WsdlToPhp/PackageGenerator#in-a-project-1) to use the generator

**Comment by 4n70w4** [comment]
Okay, easiest way - download wsdltophp-php7.phar and use it.
