### ISSUE TITLE
Suffixes for ServiceType classes

### ISSUE THREAD

**Issue by 4n70w4** [WsdlToPhp/PackageGenerator#189]
Hi. I generated code, but the service classes and the structure classes have the same names, it very unuseful.

```
$authenticate = new \Client\ServiceType\Authenticate($options);
/**
 * Sample call for Authenticate operation/method
 */
if ($authenticate->Authenticate(new \Client\StructType\Authenticate()) !== false) {
    print_r($authenticate->getResult());
} else {
    print_r($authenticate->getLastError());
}
```

it would be more convenient to give classes suffixes:
`\Client\ServiceType\Authenticate` => `\Client\ServiceType\AuthenticateService`

It is necessary that there be no namespace name collisions.
Cannot be imported like this:

```
use Client\ServiceType\Authenticate;
use Client\StructType\Authenticate;
```

Manually assign aliases - very lazy.

**Comment by mikaelcom** [comment]
You can suffix/prefix the generated classes if necessary, see the [class naming options](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options#class-naming)
