### ISSUE TITLE
do a simple request

### ISSUE THREAD

**Issue by Spartacus2018** [WsdlToPhp/PackageGenerator#194]
Hello, 
well i m stuck using wsdltophp i using https://github.com/wsdl2phpgenerator

but it 's look like u program are more updated, i m stuck with  : 

`PHP Fatal error:  Uncaught Error: Class 'GeneratorOptions' not found in `

So to start my project : 

1> installation of the bundle : 

`composer require wsdltophp/packagegenerator`

2> Créate the class of my wsdl : 

```
<?php

require_once __DIR__ . '/vendor/autoload.php';


$url= "http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl";

use wsdltophp\packagebase\Base;
use wsdltophp\packagegenerator\Generator;

// Options definition: the configuration file parameter is optional
$options = GeneratorOptions::instance(/* '/path/file.yml' */);
  $options
      ->setOrigin($url)
      ->setDestination('./MySdk')
      ->setComposerName('myproject/mysdk');
  // Generator instantiation
  $generator = new Generator($options);
  // Package generation
  $generator->generatePackage();

```

and i get this error : 

```
serv01:/var/www/html/$ php generateWSDSL2.php
PHP Fatal error:  Uncaught Error: Class 'GeneratorOptions' not found in /var/www/html/generateWSDSL2.php:19
```

can u tell me what is wrong please 

and my second question it's adding a header option on the soap request to add a key

**Comment by mikaelcom** [comment]
All you need is:

```php
require_once __DIR__ . '/vendor/autoload.php';

use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
use WsdlToPhp\PackageGenerator\Generator\Generator;

// Options definition: the configuration file parameter is optional
$options = GeneratorOptions::instance();
$options
    ->setOrigin('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
    ->setDestination('./MySdk')
    ->setComposerName('myproject/mysdk');
// Generator instantiation
$generator = new Generator($options);
// Package generation
$generator->generatePackage();
```

For the other question, please create a new issue after generating the package and trying to send the request. Please provide the used script and the required behaviour.

_ps: using a good IDE should help you automatically adding the use statements :wink:, such as Eclipse PDT or phpStorm._

**Comment by Spartacus2018** [comment]
i put this on my files : 

`<?php

require_once __DIR__ . '/vendor/autoload.php';

$url = 'https://api-pp-test.sa-cim.fr/GED/wsImportDocGED.asmx?wsdl';


use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
use WsdlToPhp\PackageGenerator\Generator\Generator;

// Options definition: the configuration file parameter is optional
$options = GeneratorOptions::instance();
$options
    ->setOrigin('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
    ->setDestination('./MySdk')
    ->setComposerName('myproject/mysdk');
// Generator instantiation
$generator = new Generator($options);
// Package generation
$generator->generatePackage();`


but i still have this respons : 

what do u think please : 

```
PHP Fatal error:  Uncaught Error: Class 'GeneratorOptions' not found in /generateWSDSL2.php:24
Stack trace:
#0 {main}
  thrown in /generateWSDSL2.php on line 24
```

**Comment by Spartacus2018** [comment]
Ok works :)
