### ISSUE TITLE
Litlle problem using comprehension

### ISSUE THREAD

**Issue by ghost** [WsdlToPhp/PackageGenerator#196]
Hello there, 

so i using wsdlToPhp to generate my php class cool

my wsdl like i imagine it  : 

class programInstance

function authenticate (user,passsword)
function getRequest(arrayInfo)
function modificationRequest(arrayInfo)

but the class generate by wsdltophp is 

programSDK 
     - src
          - ArrayType
           - serviceType
           - structureType

so now i got all my methode separely

but if i want start a request i have to do : 

$instance = new programinstance ();
$instance->authenticate($login, $password);
$instance->modificationRequest($ârrayInfo)

but with wsdlPHP how i can create instance class ? i hvae to create it myself ?

how instance a class and all stuff like a methode, something escape me

thanks for u help

**Comment by mikaelcom** [comment]
I'm not sure to understand your issue which does not seem to relate to the generator but more about an architectural matter, does it ?

I would say, it's up to you :wink:

**Comment by Spartacus2018** [comment]
Hello yes 

It s an architecture problème

I m still not unserstand how use code generate ??

I have tu create an classe with all object to use ??

**Comment by mikaelcom** [comment]
If you need help developing, I can work with you, contact me at contact@mikael-delsol.fr (in French if preferable for you), not free nonetheless :).

**Comment by mikaelcom** [comment]
no news, good news?
