### ISSUE TITLE
wsdltophp.com (works) and offline code not producing same result

### ISSUE THREAD

**Issue by Teknia** [WsdlToPhp/PackageGenerator#197]
I used the same wsdl (publicly available at http://www.dneonline.com/calculator.asmx?wsdl) to generate a set of classes for PHP. I tested it on my localhost and it works fine.

I downloaded the phar file and generated a new set of php classes from the same wsdl. It generates it, but when testing on my local host I get a few errors. The summary of the errors are:
- System.InvalidOperationException: There is an error in XML document (2, 147).  ---> System.FormatException: Input string was not in a correct format

My command line was:
./wsdltophp.phar generate:package --urlorpath="http://www.dneonline.com/calculator.asmx?wsdl" --destination="output4" --composer-name="myproject2/mypackage2" --force

Notes: 
- The WSDL has not changed. It points to the same file.
- I removed all the functions in tutorial.php apart from Add, in both cases, since only Add is implemented on the webservice.
- I had to add the disable-tls in the composer.json file to get it to work.

Please advise.

**Comment by mikaelcom** [comment]
I'm not sure to understand when the error occurs: when generating the package or when sending the request?

**Comment by Teknia** [comment]
The error occurs when sending the Add request, but since this works fine for the code that was generated online, I assume the code that was generated offline has a problem since nothing else changed in the WSDL or service.

**Comment by mikaelcom** [comment]
Did you try to make a _diff_ (with git for example)? Because I don't see what could differ

**Comment by Teknia** [comment]
The two generated classes have very different coding 'styles' so a diff will just highlight all. I will attach both Add classes for manual comparison.

Note: 
- CalculatorWsdlServiceAdd.zip is the file from the set that works (generated online)
- Add.zip is the file from the set that gives the run-time error when calling tutorial.php.

[Add.zip](https://github.com/WsdlToPhp/PackageGenerator/files/3313322/Add.zip)
[CalculatorWsdlServiceAdd.zip](https://github.com/WsdlToPhp/PackageGenerator/files/3313329/CalculatorWsdlServiceAdd.zip)

**Comment by mikaelcom** [comment]
Ok so one is from https://www.wsdltophp.com and the other one if from the new generator version.

If I'm right, for your information the new generator is better and so is the generated code. You should use the new platform too from https://providr.io.

That being said, if I use the generated package on https://providr.io with the Send requests feature, it works fine. Try debugging the sent XML request and HTTP headers to see if everything is allright:
![add](https://user-images.githubusercontent.com/584391/59905202-c73e3180-9405-11e9-9d1c-99aaa1e51497.png)

**Comment by mikaelcom** [comment]
no news, good news?
