### ISSUE TITLE
generated request is not XML ?

### ISSUE THREAD

**Issue by nohavy** [WsdlToPhp/PackageGenerator#198]
Hello,

i try to use your lib to generate a package for my project.

The package is generated from 
`./wsdltophp-php7.phar generate:package --urlorpath="https://webservices.recette.maileva.com/java/public/connector/ConnectorWebService?wsdl" --destination="./MailevaSDK"     --composer-name="region/maileva" --force`

First problem, the lib create a class StructType/Document_1.php that should not exist. I manage this problem by hand, replacing in StructType/Documents.php the class Document_1 by the good one Document (StructType/Document.php).

When i do a request, the generated request by SoapClient is not in XML. It is a simple string.

The call 
`
       $options = [
            \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => $this->wsdl_depot,
            \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => ClassMap::get(),
            \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_TRACE => true,
            \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_LOGIN => $this->login_http,
            \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_PASSWORD => $this->password_http,
        ];

        $client = new \ServiceType\Submit($options);
        $trackID = "testregion1";
        
        $addressLines = new \StructType\AddressLines('Dupond Etienne', '1 rue Victoire', '', '', '', '75001 Paris');
        $paperAddress = new \StructType\PaperAddress($addressLines, null, null, null);
        $recipient = new \StructType\Recipient('recipient1', $paperAddress, null, null, null, null, null, null, $trackID, null);
        $internal = new \StructType\Internal([$recipient]);
        $recipients = new \StructType\Recipients($internal);

        $documentContent = new \StructType\DocumentContent(file_get_contents(__DIR__ . "/template/courrier_test.pdf"));
        $document = new \StructType\Document('document1', null, null, null, null, $documentContent);
        $documents = new \StructType\Documents([$document]);
        $documentData = new \StructType\DocumentData(null, $documents);

        $pageOptionPaper = new \StructType\PageOptionPaper(boolval($this->couleur));
        $documentOptionPaper = new \StructType\DocumentOptionPaper(boolval($this->recto_verso), $pageOptionPaper);
        $foldOptionPaper = new \StructType\FoldOptionPaper($this->enveloppe, $this->type_fenetre, $this->affranchissement, null, null, null, null, null, null, null, null, null, null, null, null, $documentOptionPaper);
        $paperOption = new \StructType\RequestOptionPaper(null, null, null, null, null, null, $foldOptionPaper, null);
        $requestOption = new \StructType\RequestOption($paperOption, null, null, null, null);
        $mailOptions = new \StructType\Options($requestOption, null, null, null);

        $protocol = new \StructType\Protocol('test@test.com', null, null, null, null, null);
        $protocols = new \StructType\Protocols([$protocol]);
        $notification = new \StructType\Notification('GENERAL', 'TXT', null, $protocols);
        $notifications = new \StructType\Notifications([$notification]);

        $request = new \StructType\Request('PAPER', $recipients, null, $documentData, $mailOptions, null, $notifications, null, $trackID, null);
        $requests = new \StructType\Requests([$request]);
        $campaign = new \StructType\Campaign($requests, 'RégionRéunionTest', $trackID, null, 'PastellRR974', null);
        $submit = new \StructType\Submit($campaign);
        
        if ($client->submit($submit) !== false) {
            // return '<pre>' . print_r($client->getResult(), -1) . '</pre>';
            return '<pre>' . print_r($client->getFormatedXml($client->getLastRequest()), -1) . '</pre>';
        } else {
            return '<pre>' . print_r($client->getLastError(), -1) . '</pre>';
        }
`
Parameters send to SoapClient 
`
object(StructType\Submit)#56 (1) { ["campaign"]=> object(StructType\Campaign)#53 (6) { ["Requests"]=> object(StructType\Requests)#19 (1) { ["Request"]=> array(1) { [0]=> object(StructType\Request)#67 (10) { ["MediaType"]=> string(5) "PAPER" ["Recipients"]=> object(StructType\Recipients)#82 (1) { ["Internal"]=> object(StructType\Internal)#83 (1) { ["Recipient"]=> array(1) { [0]=> object(StructType\Recipient)#84 (10) { ["Id"]=> string(10) "recipient1" ["PaperAddress"]=> object(StructType\PaperAddress)#85 (4) { ["AddressLines"]=> object(StructType\AddressLines)#86 (6) { ["AddressLine1"]=> string(13) "Dupond Etienne" ["AddressLine2"]=> string(14) "1 rue Victoire" ["AddressLine3"]=> string(0) "" ["AddressLine4"]=> string(0) "" ["AddressLine5"]=> string(0) "" ["AddressLine6"]=> string(9) "75001 Paris" } ["Country"]=> NULL ["CountryCode"]=> NULL ["InvoiceAddress"]=> NULL } ["FaxAddress"]=> NULL ["EmailAddress"]=> NULL ["SmsAddress"]=> NULL ["DigitalAddress"]=> NULL ["Category"]=> NULL ["HasDigitalId"]=> NULL ["TrackId"]=> string(11) "testregion1" ["PartnerTrackId"]=> NULL } } } } ["Senders"]=> NULL ["DocumentData"]=> object(StructType\DocumentData)#78 (2) { ["MergeFields"]=> NULL ["Documents"]=> object(StructType\Documents)#79 (1) { ["Document"]=> array(1) { [0]=> object(StructType\Document)#80 (7) { ["Id"]=> string(9) "document1" ["Shrink"]=> NULL ["Size"]=> NULL ["Hash"]=> NULL ["MergeFields"]=> NULL ["Content"]=> object(StructType\DocumentContent)#81 (3) { ["Value"]=> string(109003) "%PDF-1.4 %äüöß 2 0 obj <> stream 

my endstream endobj 29 0 obj <> endobj 30 0 obj <> endobj 31 0 obj <> /ProcSet[/PDF/Text/ImageC/ImageI/ImageB] >> endobj 1 0 obj <>/Contents 2 0 R>> endobj 6 0 obj <>/Contents 7 0 R>> endobj 9 0 obj <> endobj 32 0 obj <> endobj 33 0 obj < /Producer /CreationDate(D:20190722102205+04'00')>> endobj xref 0 34 0000000000 65535 f 0000107403 00000 n 0000000019 00000 n 0000004005 00000 n 0000026687 00000 n 0000004026 00000 n 0000107572 00000 n 0000042119 00000 n 0000043545 00000 n 0000107741 00000 n 0000043566 00000 n 0000067053 00000 n 0000067076 00000 n 0000067267 00000 n 0000067899 00000 n 0000068371 00000 n 0000086276 00000 n 0000086299 00000 n 0000086500 00000 n 0000087040 00000 n 0000087423 00000 n 0000103712 00000 n 0000103735 00000 n 0000103931 00000 n 0000104395 00000 n 0000104707 00000 n 0000106565 00000 n 0000106587 00000 n 0000106779 00000 n 0000107070 00000 n 0000107231 00000 n 0000107294 00000 n 0000107846 00000 n 0000107943 00000 n trailer < <28BDCCDDBA64E6ED45EE18F0D9D83831> ] /DocChecksum /49B978B734E48D7AE6E2AA9AAE6712DA >> startxref 108118 %%EOF " ["Uri"]=> NULL ["encoding"]=> NULL } ["DocumentType"]=> NULL } } } } ["Options"]=> object(StructType\Options)#72 (4) { ["RequestOption"]=> object(StructType\RequestOption)#73 (5) { ["PaperOption"]=> object(StructType\RequestOptionPaper)#74 (8) { ["ExpectedGrouping"]=> NULL ["GroupingDate"]=> NULL ["ExpectedSplitting"]=> NULL ["StampAdjust"]=> NULL ["RemoveInvalidReturnEnvelope"]=> NULL ["DocumentsRestitution"]=> NULL ["FoldOption"]=> object(StructType\FoldOptionPaper)#75 (18) { ["EnvelopeType"]=> string(2) "C6" ["EnvelopeWindowType"]=> string(4) "SMPL" ["PostageClass"]=> string(8) "STANDARD" ["PrintSenderAddress"]=> NULL ["PrintRecipAddress"]=> NULL ["ClearSenderArea"]=> NULL ["ClearRecipArea"]=> NULL ["PrintRecipTrackId"]=> NULL ["TreatUndeliveredMail"]=> NULL ["TreatAR"]=> NULL ["DigitalArchiving"]=> NULL ["GroupingPriority"]=> NULL ["UseFlyLeaf"]=> NULL ["LogoRef"]=> NULL ["ReturnEnvelopeRef"]=> NULL ["DocumentOption"]=> object(StructType\DocumentOptionPaper)#76 (3) { ["PrintDuplex"]=> bool(true) ["PageOption"]=> object(StructType\PageOptionPaper)#77 (3) { ["PrintColor"]=> bool(true) ["BackgroundId"]=> NULL ["InsertPageId"]=> NULL } ["Staple"]=> NULL } ["SwitchingPolicy"]=> NULL ["ForceSendingMode"]=> NULL } ["InvoiceOption"]=> NULL } ["FaxOption"]=> NULL ["EmailOption"]=> NULL ["SmsOption"]=> NULL ["DigitalOption"]=> NULL } ["FoldOptions"]=> NULL ["DocumentOptions"]=> NULL ["PageOptions"]=> NULL } ["Folds"]=> NULL ["Notifications"]=> object(StructType\Notifications)#68 (1) { ["Notification"]=> array(1) { [0]=> object(StructType\Notification)#69 (4) { ["Type"]=> string(7) "GENERAL" ["Format"]=> string(3) "TXT" ["Language"]=> NULL ["Protocols"]=> object(StructType\Protocols)#70 (1) { ["Protocol"]=> array(1) { [0]=> object(StructType\Protocol)#71 (6) { ["Email"]=> string(27) "test@test.com" ["Ftp"]=> NULL ["Cft"]=> NULL ["Http"]=> NULL ["Ws"]=> NULL ["NotificationCenter"]=> NULL } } } } } } ["ProductionDate"]=> NULL ["TrackId"]=> string(11) "testregion1" ["MediaSubType"]=> NULL } } } ["Name"]=> string(19) "RégionRéunionTest" ["TrackId"]=> string(11) "testregion1" ["PartnerTrackId"]=> NULL ["Application"]=> string(12) "PastellRR974" ["BreakdownCode"]=> NULL } } 
`

And the __getLastRequest is a String instead of XML
`
string(147213) " Dupond Etienne1 rue Victoire75001 ParisJVBERi0xLjQKJcOkw7zDtsOfCjIgMCBvYmoKPDwvTGVuZ3RoIDMgMCBSL0ZpbHRlci9GbGF0ZURlY29kZT4+CnN0cmVhbQp4nKVbW4sstxF+318xz4Zdt0pqqRuWgdnZWUjeDAfyYPKUxDHBJ8F+yd+P6qKqkvqyxzELszPdUqnu+qrUPb2Ey3+ffr2EaXkplxLzS7p8feJfS4j11y+XOS4v8/ALwgvgj1zH8fcn+s4Ufuno/XL5+SnF9SVe5lR/rvhRf8Llt388/eW7y7+fwgX[// i truncate the base64//]C6SMPLSTANDARDtruetrueTXTtest@test.com" 
`

Can you give me some advices ?

**Comment by mikaelcom** [comment]
The Document_1 is indeed useless but mainly results from the declaration from the WSDL and its schemas. You maintly have to remove the entry in the ClassMap class `'Document' => '\\StructType\\Document_1',` and it should ensure that if the response contains a Document object, the SoapClient will us the first Document class.

Concerning the sent request, I succeeded to get this request (not full but it's the spirit ;)):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.maileva.fr/CommonSchema" xmlns:ns2="http://www.maileva.fr/MailevaPJSSchema" xmlns:ns3="http://www.maileva.fr/MailevaSpecificSchema" xmlns:ns4="http://connector.services.siclv2.maileva.fr/">
  <SOAP-ENV:Body>
    <ns4:submit>
      <campaign Name="RégionRéunionTest" TrackId="testregion1" PartnerTrackId="" Application="PastellRR974" BreakdownCode="">
        <ns2:Requests>
          <ns2:Request MediaType="PAPER" TrackId="">
            <ns2:Recipients>
              <ns2:Internal>
                <ns2:Recipient Id="recipient1" TrackId="" PartnerTrackId="">
                  <ns1:PaperAddress>
                    <ns1:AddressLines>
                      <ns1:AddressLine1>Dupond Etienne</ns1:AddressLine1>
                      <ns1:AddressLine2>1 rue Victoire</ns1:AddressLine2>
                      <ns1:AddressLine3/>
                      <ns1:AddressLine4/>
                      <ns1:AddressLine5/>
                      <ns1:AddressLine6>75001 Paris</ns1:AddressLine6>
                    </ns1:AddressLines>
                    <ns1:Country/>
                    <ns1:CountryCode>FR</ns1:CountryCode>
                  </ns1:PaperAddress>
                  <ns1:Category/>
                </ns2:Recipient>
              </ns2:Internal>
            </ns2:Recipients>
            <ns2:Notifications>
              <ns2:Notification Type="GENERAL">
                <ns3:Format>TXT</ns3:Format>
                <ns3:Language/>
                <ns3:Protocols>
                  <ns3:Protocol>
                    <ns3:Email>test@test.com</ns3:Email>
                  </ns3:Protocol>
                </ns3:Protocols>
              </ns2:Notification>
            </ns2:Notifications>
          </ns2:Request>
        </ns2:Requests>
      </campaign>
    </ns4:submit>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

I can provide help, contact me at contact@mikael-delsol.fr (in Freng if native language)

**Comment by mikaelcom** [comment]
now news, good news?
