### ISSUE TITLE
infinite loops on circular include/import references

### ISSUE THREAD

**Issue by greggreenhaw** [WsdlToPhp/PackageGenerator#202]
The following wsdl creates an infinite loop
https://gmdealerservices.gm.com/DCDEService/2.0?wsdl

**Comment by mikaelcom** [comment]
I got an error when trying to load the WSDL with SoapClient due to, at the least, an invalid URL https://gmdealerservices.gm.com/ssg/wsdl/STARWSDLDataTypes4.xsd?serviceoid=f5893f4d9b48115f8744cc885591fdf8&servdocoid=f5893f4d9b48115f8744cc885591fe41:
```
Invalid service requested
```

**Comment by greggreenhaw** [comment]
OH sorry try this one.
https://gmdealerservices.pp.gm.com/DCDEService/2.0?wsdl

**Comment by mikaelcom** [comment]
Probably due from this "looping" declaration:
```xml
  <xsd:simpleType name="CurrencyCodeContentType">
    <xsd:union memberTypes="clm54217:CurrencyCodeContentType"/>
  </xsd:simpleType>
```

**Comment by greggreenhaw** [comment]
Is that a loop its another namespace?

**Comment by mikaelcom** [comment]
Namespaces are not taken into account by the parsers currently, which by the way has never been an issue yet.

So currently, the `CurrencyCodeContentType` is considered as having an union with itself wich fails while generating the sources.

I just found a fix, try the [feature/issue-202](https://github.com/WsdlToPhp/PackageGenerator/compare/feature/issue-202) branch please then let me know how it goes using the generated sources.

**Comment by greggreenhaw** [comment]
I guess I can change the xsd to this and avoid the union

<xsd:simpleType name="CurrencyCodeContentType">
     <xsd:restriction base="xsd:normalizedString">
      <xsd:enumeration value="USD">
        <xsd:annotation>
          <xsd:documentation>
            <CodeName>US Dollar</CodeName>
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>
      </xsd:restriction>
  </xsd:simpleType>

**Comment by mikaelcom** [comment]
> Is you fix just to ignore the union even though its importing valid values?

Currently the targetted namespace points to an invalid URI so I can't say there are valid values in this particular case.

> Can you generate a phar file for me?
Download the content from either one of the two URLs depending on your PHP version:
* https://phar.wsdltophp.com/wsdltophp-feature-issue-202-php5.phar
* https://phar.wsdltophp.com/wsdltophp-feature-issue-202-php7.phar

**Comment by mikaelcom** [comment]
> I guess I can change the xsd to this and avoid the union
> 
> <xsd:simpleType name="CurrencyCodeContentType">
> <xsd:restriction base="xsd:normalizedString">
> <xsd:enumeration value="USD">
> xsd:annotation
> xsd:documentation
> US Dollar
> </xsd:documentation>
> </xsd:annotation>
> </xsd:enumeration>
> </xsd:restriction>
> </xsd:simpleType>

The declaration below
```xml

  <xsd:simpleType name="CurrencyCodeContentType">
    <xsd:union memberTypes="clm54217:CurrencyCodeContentType"/>
  </xsd:simpleType>
```
is from the CodeLists_1.xsd file.

**Comment by greggreenhaw** [comment]
Changing the wsdl didn't seem to fix it.  
I noticed there are these references to unqualified data types using the udt: prefix could this be an issue?

 <xsd:complexType name="AmountType">
    <xsd:simpleContent>
      <xsd:extension base="udt:AmountType"/>
    </xsd:simpleContent>
  </xsd:complexType>

**Comment by mikaelcom** [comment]
I personnally succeeded to generate the package with the latest fix, didn't you?

**Comment by greggreenhaw** [comment]
Thank You for your help I really appreciate it.

Yes I guess I had been tweaking my local copy and the updated version broke but the remote copy of the WSDL worked. 

Is you change skipping all unions where the member class name = the simple type name? 

As far as the qualified uri in the original WSDL
<xsd:union memberTypes="clm54217:CurrencyCodeContentType"/>
The prefix clm54217 was defined at the top and pointed to the following. Is that not valid?
xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001"

**Comment by mikaelcom** [comment]
> Thank You for your help I really appreciate it.
> 
> Yes I guess I had been tweaking my local copy and the updated version broke but the remote copy of the WSDL worked.
> 
> Is you change skipping all unions where the member class name = the simple type name?

I'm not 100% sure of what you're saying but I would say yes.

> As far as the qualified uri in the original WSDL
> <xsd:union memberTypes="clm54217:CurrencyCodeContentType"/>
> The prefix clm54217 was defined at the top and pointed to the following. Is that not valid?
> xmlns:clm54217="http://www.openapplications.org/oagis/9/currencycode/54217:2001"

Did you try loading http://www.openapplications.org/oagis/9/currencycode/54217:2001 with your browser ? :wink:

**Comment by greggreenhaw** [comment]
Namespace uris are rarely valid for example  xmlns:star="http://www.starstandard.org/STAR/5"

**Comment by mikaelcom** [comment]
merged a while ago :)
