### ISSUE TITLE
namespace must not match the enclosing schema 'targetNamespace'

### ISSUE THREAD

**Issue by greggreenhaw** [WsdlToPhp/PackageGenerator#203]
The following wsdl is throws this error. Not sure how to correct. I'm not seeing any validation errors.

https://gmdealerservices.gm.com/gmCard/getCustomerInformation?wsdl

  SOAP-ERROR: Parsing Schema: can't import schema from 'https://gmdealerservices.gm.com/ssg/wsdl/getCustomerInformation.xsd?serviceoid=7fffffffffffffff00000000012d8006&servdocoid=8749c5450a564adda9dc300645fccb6c', namespace must not match the enclosing schema 'targetNamespace'

**Comment by greggreenhaw** [comment]
Changing the imports to includes seem to have worked. Not sure its correct though
<xsd:include  schemaLocation="getCustomerInformation.xsd"/>
      <xsd:include schemaLocation="ExtShowCustomerInformation.xsd"/>

**Comment by mikaelcom** [comment]
This has nothing to do with the generator, closing.
