### ISSUE TITLE
Overwriting existing files

### ISSUE THREAD

**Issue by daCyberpunk** [WsdlToPhp/PackageGenerator#204]
Hi!
Thank you a lot for that nice tool. Saves me a lot of time.

In my case I am using this to generate the classes via cli during a composer install/update. 
For the moment I use only some of the classes, the others I throw away. 

The classes which I am using, I want to to refactor them a little.

In case, I want to use other classes later too, I have to regenerate everything. But then the generator is overwriting my reworked classes. 
For now I am generating everything in a seperate folder and move them via cli to the final destination. 

But it would be much more comfortable to have an simple "no-override" option.
I couldn't found anything, am I right?

Best!

**Comment by mikaelcom** [comment]
Hi,
Did you try using inhertited classes or proxy classes instead of using the generated classes?
It would then allwo to always overwrite the generated classes without being worried of losing your proper code.

There is currently no option as *no-override*.

Let me know

**Comment by mikaelcom** [comment]
closing as no response has been provided
