### ISSUE TITLE
Inherited class generates wrong object in php.

### ISSUE THREAD

**Issue by phryneas** [WsdlToPhp/PackageGenerator#21]
Hi,
I have a structure like this in my C# soap service:
```
    [DataContract]
    public class order
    {
...
    }

    [DataContract]
    public class offer : order
    {
...
    }
```

which results in this PHP code:

```

class MyOffer extends MyOrder 
{
// all Attributes from offer are here

    /**
     * The offer
     * Meta informations extracted from the WSDL
     * - minOccurs: 0
     * - nillable: true
     * @var order
     */
    public $offer;

    /**
     * Set offer value
     * @param order $offer
     * @return \MyNameSpace\StructType\MyOffer
     */
    public function setOffer(order $offer = null)
    {
        $this->offer = $offer;
        return $this;
    }

}
```

So even though it already extends MyOrder as expected, it also adds an attribute "offer" of type "order" - the class "order" of course does not exist in php, as it is mapped to MyOrder.

This happens on the latest dev-master commit.

If you need any XSD files for debugging, I'd be happy to provide you those in private email, but I'd rather not append these to this public ticket. Just send me an email to mail@lenzw.de :)

**Comment by phryneas** [comment]
What I forgot: this could be related to some "merging" of the service parameter class and the normal struct.

In C#, I have the OperationContracts
```
        String booking(order booking);
        String offer(offer offer);
```

Which results in the 
generation of these Method/Class signatures:

```
ServiceType\MyBooking->booking(\MyNameSpace\StructType\MyBooking $parameters)
StructType\MyBooking->setBooking(\MyNameSpace\StructType\MyOrder $booking = null)
StructType\MyOrder
```
and on the other hand
```
ServiceType\MyOffer->offer(\MyNameSpace\StructType\MyOffer $parameters)
StructType\MyOffer->setOffer(order $offer = null)
```

**Comment by phryneas** [comment]
I created a repo with a small project for reproduction at https://github.com/phryneas/testproject-reproduce-bug-wsdl-to-php - the wsdl is available there, too.

**Comment by mikaelcom** [comment]
I forked your repo [here](https://github.com/WsdlToPhp/testproject-reproduce-bug-wsdl-to-php) and added the generated package after the fix.

Could you validate that it is what you're expecting ?

Thanks,

**Comment by phryneas** [comment]
Yes, that's much better.
* it extends from the correct class
* it contains a setter for the offer class as if it were the parameter-type class
* it contains a setter for members as if it were the struct class
* @param comments point to the correct types.

For my special use case this should fix all problems.

There may be one potential edge case for others though:

Assume the offer-class had a class member named offer, that itself would not be of type WcfOffer.
Could this be handled by the WcfOffer->setOffer method, or would this result in two conflicting method signatures for a method with the same name in the same class?

The only solution for this that I could think of would be moving the parameter classes into a namespace separate from the struct classes.

**Comment by mikaelcom** [comment]
If it works for your case, I'll wait for the other case to happen to implement its handling, I prefer not to overload the code if it's not necessary

**Comment by phryneas** [comment]
That's a good point :)

Thank you! :+1:
