### ISSUE TITLE
Feature: Actual versions docker images on docker hub

### ISSUE THREAD

**Issue by 4n70w4** [WsdlToPhp/PackageGenerator#221]
Hi! I could not find on the hub docker images of this project.
It would be convenient to have an images with actual versions on a docker hub.

**Comment by 4n70w4** [comment]
Draft Dockerfile:

```Dockerfile
ARG PHP=7.4.10
ARG WSDLTOPHP=3.2.7

FROM php:$PHP-cli

ARG WSDLTOPHP

RUN apt-get update && apt-get install -y libxml2-dev && docker-php-ext-install -j$(nproc) soap

ADD https://github.com/WsdlToPhp/PackageGenerator/releases/download/$WSDLTOPHP/wsdltophp-$WSDLTOPHP-php7.phar wsdltophp.phar

RUN chmod +x wsdltophp.phar

ENTRYPOINT /wsdltophp.phar
```


Build:

```bash
WSDLTOPHP=3.2.7; docker build -t wsdltophp:$WSDLTOPHP --build-arg WSDLTOPHP=$WSDLTOPHP .
```


Check:

```bash
docker run --rm -it wsdltophp:3.2.7 -v
```

Now need to automatically build images for each version and upload them to the docker hub.

It can be used in CI / CD pipelines:

```bash
docker run --entrypoint php --rm -it -v $(pwd)/gen.php:/gen.php -v $(pwd)/src:/src wsdltophp:3.2.7 gen.php
```



gen.php example:


```php
<?php

require_once 'phar:///wsdltophp.phar/vendor/autoload.php';

use WsdlToPhp\PackageGenerator\ConfigurationReader\GeneratorOptions;
use WsdlToPhp\PackageGenerator\Generator\Generator;


$wsdls = [
    'ServiceV1.svc?wsdl' => [
        'src' => '/src/ServiceV1/',
        'ns' => 'ServiceV1',
    ],

];

foreach($wsdls as $wsdl => $settings) {

    $options = GeneratorOptions::instance();

    $options
        ->setOrigin($wsdl)
        ->setDestination($settings['src'])
        ->setNamespace($settings['ns'])
        // ->setSoapClientClass(SoapClientBase::class)

        // no composer.json needed
        ->setStandalone(false)

        // no tutorial.php file needed
        ->setGenerateTutorialFile(false)

        // no src folder needed for the generated package
        ->setSrcDirname('');

    $generator = new Generator($options);
    $generator->generatePackage();

    fwrite(STDOUT, PHP_EOL . $settings['src'] . ' / ' . $settings['ns']);
}

```

**Comment by mikaelcom** [comment]
Hi, after a few commits :sweat_smile: I think I finally achieved what I wanted in order to answer to your feature using Github Actions which avoids me some work. I still have an issue with the "Build and push to Docker" step which is still executed even if the current Job PHP version is not 7 :disappointed:, a few commits are coming again ;), if you have any clue, feel free to guide me ;).

Let me know if it works as expected from https://hub.docker.com/repository/docker/mikaelcom/wsdltophp. Readme is coming soon too at Docker hub.

**Comment by mikaelcom** [comment]
> Hi, after a few commits  I think I finally achieved what I wanted in order to answer to your feature using Github Actions which avoids me some work. I still have an issue with the "Build and push to Docker" step which is still executed even if the current Job PHP version is not 7 , a few commits are coming again ;), if you have any clue, feel free to guide me ;).
> 
> Let me know if it works as expected from https://hub.docker.com/r/mikaelcom/wsdltophp. Readme is coming soon too at Docker hub.

The docker image is now only built using the PHP 7 version then pushed to the Docker Hub platform :wink:.

With this setup, each time a tag will be created:
- the Phar file is generated for PHP 5 and 7
- the release draft is created for PHP 5 and 7
- the phar file is uploaded within the release draft for PHP 5 and 7
- if the PHP version is 7, then the Docker image is generated and published on Docker Hub

**Comment by 4n70w4** [comment]
Hi! It is desirable that the filename be with the phar extension.

```php
require_once 'phar:///wsdltophp/vendor/autoload.php';
```

```
Warning: require_once(phar:///wsdltophp/vendor/autoload.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///wsdltophp/vendor/autoload.php" in /gen.php on line 4
```

**Comment by mikaelcom** [comment]
So, to be clear, for me :), using the image in a command line right away without any php script would be:
```bash
$ docker run --entrypoint php --rm -it mikaelcom/wsdltophp:tagname wsdltophp.phar generate:package ... --force
```

**Comment by mikaelcom** [comment]
Hi, did you have some time to try it out?

I think it's good to go, let me know ;)
Thx

**Comment by 4n70w4** [comment]
Sorry, I haven't looked yet, now there are other tasks (
