### ISSUE TITLE
PHP 7.4 or PHP 8?

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#223]
I'm noticing there is nothing listed for support of PHP 7.4 and nothing for the upcoming 8.0 release.  Is there any reason for this?  Is this project not going to be continuing?  It appears that there is at least some changes still occurring, so with the 8.0 release looming I thought I'd ask.

Thanks,

Kevin

**Comment by mikaelcom** [comment]
Hi, I'm always glad to work on the projet especially if there is feedback such yours even if I do not work on it on daily basis.

There is currently 2 issues I'd like to close, https://github.com/WsdlToPhp/PackageGenerator/issues/221 and https://github.com/WsdlToPhp/PackageGenerator/issues/219, to be packaged with the next release.

In the meantime, is there anything particular you would expect to be improved/featured/packaged thanks to PHP 7.4 and/or PHP 8?

**Comment by faithfulman18** [comment]
Hi Mikael,

Mostly I would just want it to be compatible with the new versions of PHP, so I know I can rely on this project for future WSDL to SOAP translations as I make good use of the project and have appreciated your work on this and still have many vendor connections that only support SOAP.   I'm currently still running PHP 7.3 but next year is the last year of security updates so sometime in the next year my goal is to be able to migrate to PHP 8.0 (7.4 if there is a reason I cannot more immediately move to 8.0.)

I guess I also wondered what you had planned for the future of the project since I noticed on the providr.IO website there was something mentioning translating SOAP to REST and I wasn't sure if you had planned to start a new github project or if this was going to be happening in an upcoming major release of the project.  

Also, partly because I'm working on migrating to the 3.X version of the project and have been using the 2.x version for quite awhile.  Though I admit I'm not 100% sure that it will change much in regard to my use of the project as it appears it's mainly the "self vs the "this" in reference to the SOAP client.   

But I didn't know if a 4.x version was being planned shortly and if so if I should wait and just migrate to that.  But regardless, having it compatible with PHP 7.4 and 8.0 in the near future would be very helpful.  Thanks!

**Comment by mikaelcom** [comment]
As I don't work regularly on the projet, I currently don't intend to put the 4 version on track. You can safely migrate to the 3 version which I can certainly test, thanks to Travis CI, on PHP 7.4 and 8 quickly

> Also, partly because I'm working on migrating to the 3.X version of the project and have been using the 2.x version for quite awhile. Though I admit I'm not 100% sure that it will change much in regard to my use of the project as it appears it's mainly the "self" vs the "this" in reference to the SOAP client.

Indeed, mainly the `self::` changes to the `$this->` and the 3 version uses the `wsdltophp/packagebase:~2.0` whereas the 2 version uses the `wsdltophp/packagebase:~1.0` as dependency which lighten the generated classes.

**Comment by faithfulman18** [comment]
Alright.  Yeah if you can test with the newer versions of php that would be great.

**Comment by mikaelcom** [comment]
Just so you know https://github.com/WsdlToPhp/PackageGenerator/commit/37b1eee22a7d8f490cbdb0a83aefc190e3f69a01 ;)

**Comment by faithfulman18** [comment]
Great!!  So, sounds like this change will make it compatible with php 7.4 and 8.0?

**Comment by mikaelcom** [comment]
> (At least when the changes are complete?

That's right, that's the goal, for both the generator and the generated code :partying_face:

**Comment by mikaelcom** [comment]
@faithfulman18 comments are welcome at https://github.com/WsdlToPhp/PackageGenerator/pull/234
