### ISSUE TITLE
Dependency Abondoned

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#225]
Should this dependency be replaced?  It appears it has been abandoned:

https://github.com/sebastianbergmann/php-token-stream/

?

**Comment by mikaelcom** [comment]
`phpunit/php-token-stream` is required by `phpunit/php-code-coverage` which is required by `phpunit/phpunit` in dev env only so I think it's not important right now and it'll be *fixed* by sebastianbergmann one day

**Comment by faithfulman18** [comment]
Alright.  I thought I'd at least bring it to your attention.    Thanks.

**Comment by mikaelcom** [comment]
ok, thx

**Comment by Naktibalda** [comment]
This deprecation message will disappear when this project implements support for PHPUnit 9.
