### ISSUE TITLE
Signatures for .phar releases?

### ISSUE THREAD

**Issue by mwolff-fn** [WsdlToPhp/PackageGenerator#226]
I tried to get your .phar releases into the phar.io repository, so the package generator could be installed and automatically updated via Phive. Unfortunately, my proposal was declined because your releases do not provide signatures:

https://github.com/phar-io/phar.io/pull/90

Do you have any plans on providing those?

**Comment by mikaelcom** [comment]
I could, I must learn how to :wink:

**Comment by mikaelcom** [comment]
I worked on creating the phar signature that is now published along with the phar file, please let me know how it goes

**Comment by mikaelcom** [comment]
I just created the PR https://github.com/phar-io/phar.io/pull/94
