### ISSUE TITLE
SoapClient

### ISSUE THREAD

**Issue by pcualmac** [WsdlToPhp/PackageGenerator#236]
[RateService_v28.txt](https://github.com/WsdlToPhp/PackageGenerator/files/6003002/RateService_v28.txt)

Sorry for this question.

I got a problem in initialize the SoapClient.

```php
$this->setResult($this->getSoapClient()->__soapCall('getRates', array(
                $rateRequest,
            ), array(), array(), $this->outputHeaders));
```

**Comment by mikaelcom** [comment]
Can you paste the whole script instantiating the Service class? Did you look to the tutorial.php file at first?

**Comment by pcualmac** [comment]
$generator = new \Wsdl2PhpGenerator\Generator();
$files = Storage::disk('public')->allFiles('_wsdl');
foreach ($files as $key => $value) 
{                                         
    $options->setOrigin(storage_path().'/app/public/'.$value)
        ->setDestination('./sd-FedExRateService')
        ->setComposerName('sdsomersetdesign/sdfedexrateservice');                                                                            
    $generator = new Generator($options);                                        
    $generator->setOptionNamespacePrefix("FedexRateService");                    
    $generator->generatePackage();  
}

**Comment by mikaelcom** [comment]
To resume your script and its result:
- The Classes generated under the `./sd-FedExRateService/src` directory with at least:
    - `./sd-FedExRateService/src/StructType/`: containing StructType classes
    - `./sd-FedExRateService/src/ServiceType/`: containing ServiceType classes
    - `./sd-FedExRateService/src/ClassMap.php`: containing the ClassMap class
- The `tutorial.php` file is generated under the `./sd-FedExRateService` directory. It's the boilerplate to send requests using the generated classes.
- The `composer.json` file is generated under the `./sd-FedExRateService` directory
- The `composer.lock` file should be present in the `./sd-FedExRateService` directory
- The `vendor` directory should be present in the `./sd-FedExRateService` directory

Do you actually have the listed classes, files and directories?

**Comment by pcualmac** [comment]
The Classes generated under the ./sd-FedExRateService/src directory with at least:
./sd-FedExRateService/src/StructType/: containing StructType classes
./sd-FedExRateService/src/ServiceType/: containing ServiceType classes
./sd-FedExRateService/src/ClassMap.php: containing the ClassMap class

Yes

The tutorial.php file is generated under the ./sd-FedExRateService directory. It's the boilerplate to send requests using the generated classes.

Yes 

The composer.json file is generated under the ./sd-FedExRateService directory
The composer.lock file should be present in the ./sd-FedExRateService directory
The vendor directory should be present in the ./sd-FedExRateService directory

Yes


Fixed now i got an Authentication Failed error but this is on me.

Thanks
