### ISSUE TITLE
set the url for sent the request

### ISSUE THREAD

**Issue by pcualmac** [WsdlToPhp/PackageGenerator#237]
Sorry for this question.
:)

How do i set the url for send the request

**Comment by mikaelcom** [comment]
Please read the [AbstractSoapClientBase](https://github.com/WsdlToPhp/PackageBase#usage-2) usage from which the ServiceType classes inherit. You'll find the `setLocation` method that allows to set the location where the request must be sent if not defined in the WSDL.

**Comment by pcualmac** [comment]
public function getStreamContextOptions()

**Comment by pcualmac** [comment]
TESTING_URL = 'https://wsbeta.fedex.com:443/web-services/ship';

**Comment by mikaelcom** [comment]
You must call `setLocation` on the ServiceType instance:
```php
$do = new ServiceType\Do([]);
$do->setLocation(...);

$result = $do->do($parameters);
```

**Comment by pcualmac** [comment]
there is a way to output the wsdl with before is send?

**Comment by mikaelcom** [comment]
> there is a way to output the wsdl before is send?

You mean the XML request? If so, yes, you need to use the `soapclient` option such as in https://github.com/WsdlToPhp/PackageEws365/blob/develop/generate.sh and copy classes from https://github.com/WsdlToPhp/PackageEws365/tree/develop/SoapClient, then you can do whatever you need in the https://github.com/WsdlToPhp/PackageEws365/blob/develop/SoapClient/SoapClient.php class that extends the native PHP [SoapClient](https://www.php.net/manual/en/class.soapclient.php) class.

If you need more information, please open a discussion in the [Discussions tab](https://github.com/WsdlToPhp/PackageGenerator/discussions).
