### ISSUE TITLE
should be compatible with AbstractStructArrayBase::add($item)

### ISSUE THREAD

**Issue by ylrykurunovadan** [WsdlToPhp/PackageGenerator#245]
![Ekran Alıntısı2](https://user-images.githubusercontent.com/75165132/113570345-ceefba00-961c-11eb-9874-46ba8b013060.PNG)
![Ekran Alıntısı](https://user-images.githubusercontent.com/75165132/113570343-ce572380-961c-11eb-8a71-b3c5cc310ce8.PNG)
I get an error because of the type given to the variable in the function. Can you arrange it ? It works very efficiently when I delete the type. Sorry about my bad English.

**Comment by mikaelcom** [comment]
You can try the fix using Doker or the phar file from https://github.com/WsdlToPhp/PackageGenerator/releases/tag/feature%2Fissue-245
