### ISSUE TITLE
Generate package under src folder

### ISSUE THREAD

**Issue by mikaelcom** [WsdlToPhp/PackageGenerator#25]
As for any well organized project/library, it would be good to have the generated classes/files located under the src folder.

We would then have:
```bash
├── src
    ├── EnumType
        ├── << FILES >>
    ├── ServiceType
        ├── << FILES >>
    ├── StructType
        ├── << FILES >>
    ├── ClassMap.php
├── vendor
├── composer.json
├── composer.lock
└── tutorial.php
```

**Comment by insekticid** [comment]
there is no way, how to disable this weird behavior

you should define src subfolder by this parameter, that could be default --destination="src/"

I am not abble to generate clases to Symfony standard directory structure 
`--destination="src/AppBundle/Soap"`

**Comment by mikaelcom** [comment]
This is partly due to several discussions from https://github.com/WsdlToPhp/PackageGenerator/issues/8 and https://github.com/WsdlToPhp/PackageGenerator/issues/17 that lead me to always use a src folder.

Nevertheless, the default destination can't be set to `src/` as users don't always use the current directory (where you use the generator) as the destination folder. Personnally, I prefer to generate the package independently/outside from the main projet so I use the generated package as a vendor.

I also understand your position. Do you wish to make a pull request?

**Comment by insekticid** [comment]
Hi, I found another sollution, but it is borring
`php ./bin/wsdltophp.phar generate:package --urlorpath=http://xxxx/?singleWsdl --composer-name=name/soap --destination=./ --services-folder=AppBundle\\Soap\\ServiceType --enums-folder=AppBundle\\Soap\\EnumType --arrays-folder=AppBundle\\Soap\\ArrayType --structs-folder=AppBundle\\Entity --soapclient=AppBundle\\Soap\\Client --force`

**Comment by mikaelcom** [comment]
I don't see how this could work.

Are you on windows to be able to use backslashes in `AppBundle\\Soap\\ServiceType`. In addition, to be sure, the classes are still generated under the serc folder, right?

In any case, I don't understand why you couln't use the generated classes even if they are generated under the `src` folder.  Is there something I'm missing? Do you encounter autoloading issues? As you shouln't alter/modify the generated classes, I think there is no need to wonder where they are generated.

**Comment by insekticid** [comment]
This command is tested in Windows

I am using folder src but in this way src/AppBundle/Soap/ServiceType; I am distributing Symfony Bundle, so I need this folder structure

**Comment by mikaelcom** [comment]
could you try with the current develop branch using the command `php console generate:package` in order to tell me if it works as expected,
