### ISSUE TITLE
Generator not respect nillable

### ISSUE THREAD

**Issue by djdaca** [WsdlToPhp/PackageGenerator#250]
**Describe the bug**
if generate type of class properties - you not respect nillable (nullable) property in wdsl

**Expected behavior**
when you found nillable property in wdsl add ? to type of property

Sorry for my english

**Comment by djdaca** [comment]
\vendor\wsdltophp\packagegenerator\src\Model\StructAttribute.php

line 170 ++
```
public function isNillable(): bool
 {
     return 'true' === $this->getMetaValue('nillable');
 }
```

\vendor\wsdltophp\packagegenerator\src\File\Struct.php

line 66:
```
$isNullable = $attribute->isNillable();
if (false === $isNullable) {
   $isNullable = (false === $attribute->isRequired() && false === $attribute->isArray());
}

```
line 162:  same as previous

**Comment by mikaelcom** [comment]
Hi,
Can you paste a generated class having nillable properties not generated as you expect?
thx

**Comment by djdaca** [comment]
[PanOrderDetail.php.txt](https://github.com/WsdlToPhp/PackageGenerator/files/6441669/PanOrderDetail.php.txt)

**Comment by djdaca** [comment]
Thanx !

**Comment by mikaelcom** [comment]
Any chance you test the [Docker image](https://hub.docker.com/r/mikaelcom/wsdltophp/tags) or the phar file from [feature/issue-250](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/feature%2Fissue-250)?

**Comment by djdaca** [comment]
Probably on the weekend - I'm migrating to a new computer

**Comment by djdaca** [comment]
I found some time - it works, thank you very much !
