### ISSUE TITLE
Class inheritance possibly misbehaving when having restriction tag

### ISSUE THREAD

**Issue by Ionsight** [WsdlToPhp/PackageGenerator#255]
## Class inheritance possibly misbehaving when having restriction tag

When generating from  
[contactPersonFull](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=6 "extends from contactPersonExportBase") ->  
[contactPersonExportBase](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=5 "extends from contactPersonBase") ->  
[contactPersonBase](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=1 "expected base")  
  
---

[**contactPersonFull:**](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=6 "extends from contactPersonExportBase")
```xml
<xs:complexType name="contactPersonFull">
  <xs:complexContent>
    <xs:extension base="exp:contactPersonExportBase">
      <xs:sequence>
        <xs:element name="Person" type="tns:personFull">
          <xs:annotation>
            <xs:documentation>...</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="UNILogin" type="trans:uniLoginFull" minOccurs="0">
          <xs:annotation>
            <xs:documentation>...</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

[**contactPersonExportBase:**](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=5 "extends from contactPersonBase")
```xml
<xs:complexType name="contactPersonExportBase">
  <xs:complexContent>
    <xs:restriction base="d:contactPersonBase">
      <xs:attribute name="accessLevel" type="uni:KontaktpersonAdgangsniveau" use="required"/>
    </xs:restriction>
  </xs:complexContent>
</xs:complexType>
```

[**contactPersonBase:**](https://wsieksport.uni-login.dk/wsieksport-v6/ws?xsd=1 "expected base")
```xml
<xs:complexType name="contactPersonBase">
  <xs:annotation>
    <xs:documentation>...</xs:documentation>
  </xs:annotation>
  <xs:attribute name="relation" use="required" type="uni:Kontaktpersonsrelation">
    <xs:annotation>
      <xs:documentation>...</xs:documentation>
    </xs:annotation>
  </xs:attribute>
  <xs:attribute name="childCustody" type="xs:boolean" use="required">
    <xs:annotation>
      <xs:documentation>...</xs:documentation>
    </xs:annotation>
  </xs:attribute>
  <xs:attribute name="accessLevel" type="uni:KontaktpersonAdgangsniveau">
    <xs:annotation>
    <xs:documentation>...</xs:documentation>
  </xs:annotation>
</xs:attribute>
```

---

**Expectation:**
* `ContactPersonFull` should extend from `ContactPersonExportBase`
* `ContactPersonExportBase` should extend from `ContactPersonBase`

**Reality:**
* `ContactPersonFull` extends from `ContactPersonExportBase`
* `ContactPersonExportBase` **DOES NOT** extend from `ContactPersonBase`
  * Instead, `ContactPersonExportBase` extends directly from `AbstractStructBase`

**Additional context:**  
It seems that the `restriction` tag is part of the cause.

I'm unsure whether this is considered expected behavior, but I’ve tested with the dotnet-svcutil tool for .NET Core, which is behaving like I expect it to.

---

#### Regardless, do you know a way in which I can solve the issue by changing something (be it manually in the generated files, when configuring or otherwise)?

**Comment by mikaelcom** [comment]
[Restriction `base` attribute is currently not taken into account](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/Wsdl/TagRestriction.php#L113) as a way to declare an inheritance (I was not aware of that).

This is done within the [extension parser](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/Wsdl/TagExtension.php#L17) on the other hand.

To be fixed I presume :wink:

**Comment by mikaelcom** [comment]
> [Restriction `base` attribute is currently not taken into account](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/Wsdl/TagRestriction.php#L113) as a way to declare an inheritance (I was not aware of that).
> 
> This is done within the [extension parser](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/Wsdl/TagExtension.php#L17) on the other hand.
> 
> To be fixed I presume wink

I think I reviewed the code too fast last time, the inheritance from the base attribute should be handled correctly at https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/Parser/Wsdl/TagRestriction.php#L82. Any chance to get the WSDL? In the meantime, I'll try to create a local test sample

**Comment by mikaelcom** [comment]
> Regardless, do you know a way in which I can solve the issue by changing something (be it manually in the generated files, when configuring or otherwise)?

Change the generated class manually but it will eb rewritten next time you generate the package.

**Comment by mikaelcom** [comment]
Issue identified, a fix is coming :crossed_fingers:
