### ISSUE TITLE
subdirectory not converted in namespaces

### ISSUE THREAD

**Issue by lmartin59** [WsdlToPhp/PackageGenerator#256]
when a Folder option contains a sub directory  with "/" the namespace is not converted to "\\" 
exemple :  
```
$options = GeneratorOptions::instance();
            $options 
...
 ->setNamespace("App\TestWS")
                ->setStructsFolder("Domain/Entities")
                ->setServicesFolder("Infrastructure/".$service);
```

The generator create the file in the right place in App/TestWS/Domain/Entities but the namespace of structs class is : 
```
namespace App\TestWS\Domain/Entities;
```
and 
```
?\App\TestWS\Domain/Entities\CommuneDTO
```
 I took the liberty of testing a modification in the class AbstractModel line 258 
```
$namespaces[] = str_replace('/','\\',$this->getSubDirectory());
```
and it work

**Comment by mikaelcom** [comment]
Thanks for your feedback. Which version are you using?

**Comment by lmartin59** [comment]
it's wsdltophp/packagegenerator version 4.0.2
with PHP 7.4 on debian docker image

**Comment by voipminic** [comment]
I have the same problem using CLI in Debian with php7.4

**Comment by voipminic** [comment]
solved putting the namespace beteween '' ( --namespace='vendor\app\subdir' )

**Comment by mikaelcom** [comment]
I'll fix it very soon, thx for your feedback!

**Comment by mikaelcom** [comment]
This bug is also present in the 3.* versions, to be fixed :)

**Comment by mikaelcom** [comment]
Can you try with either:

- PHP < 7.4 generated code:
    - the phar from [wsdltophp-feature-issue-256-php7.phar](https://phar.wsdltophp.com/wsdltophp-feature-issue-256-php7.phar) or,
    - from the current [feature/issue-256](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-256) branch or
    - the Docker image with tag mikaelcom/wsdltophp:feature-issue-256

- PHP >= 7.4 generated code:
    - the phar from [wsdltophp-develop-php7.phar](https://phar.wsdltophp.com/wsdltophp-develop-php7.phar) or,
    - from the current [develop](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-256) branch or
    - the Docker image with tag mikaelcom/wsdltophp:develop

Thx
