### ISSUE TITLE
PHP 8.x compatibility

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#276]
**Is your feature request related to a problem? Please describe.**
I have the need to upgrade a number of projects to PHP 8.x in the very near term.  I'm hoping it might be PHP 8.2 here soon.  I don't see anything listing if there is such support and saw at least one open ticket stating it wasn't working for PHP 8.X.

**Describe the solution you'd like**
For this package to support PHP 8.x.

**Additional context**
Let me know if you need any other information.

**Comment by mikaelcom** [comment]
Unit Tests are passing using PHP 8.1.
You can use Symfony 6.* as the composer.json file allows its usage.
Let me know if you encounter any issue creating an issue :wink:

**Comment by faithfulman18** [comment]
Just to clarify ... Composer should work okay as well, right?  Is this composer 2.x compatible now?

**Comment by mikaelcom** [comment]
Currently, everything below is working:
- php81 /usr/bin/composer -v => `Composer version 2.4.3 2022-10-14 16:56:41`
- php81 /usr/bin/composer update => no warnings
- php81  vendor/bin/phpunit => `OK (779 tests, 1614 assertions)`

**Comment by faithfulman18** [comment]
Alright great.  Thank you.

**Comment by faithfulman18** [comment]
Is there somewhere from the github page that I could have known this was the case?  I don't see anything mentioned about PHP 8.x anywhere, just PHP 7.4.

**Comment by mikaelcom** [comment]
> Is there somewhere from the github page that I could have known this was the case? I don't see anything mentioned about PHP 8.x anywhere, just PHP 7.4.

I did not take the time to inform about the compatibilities, no.

**Comment by faithfulman18** [comment]
👍
