### ISSUE TITLE
XMLDSig help

### ISSUE THREAD

**Issue by omorales-sernutec** [WsdlToPhp/PackageGenerator#286]
Hello,
I'm trying to implement XMLDSig using the services your package generates.

In order to achieve this, I'm creating my own SoapClient class as done in [PackageEws365](https://github.com/WsdlToPhp/PackageEws365). With that, I can create the XMLDSig header tags based on XML body content.

The question is, once I have the headers built, how can I call the setSoapHeader method to add them.
I've done it replacing the <SOAP-ENV:Header/>string in the XML request, but I doesn't seem very clean.

Thanks for your help and for sharing your work. Very useful package.

**Comment by omorales-sernutec** [comment]
Hi,
I've figured it out using this in custom SoapClient class
https://github.com/robrichards/wse-php/blob/master/examples/soap-wsa-example.php

**Comment by mikaelcom** [comment]
Thanks for the feedback and the code sample
