### ISSUE TITLE
Wrong type for gYearMonth and gMonthDay

### ISSUE THREAD

**Issue by tbreuss** [WsdlToPhp/PackageGenerator#292]
**Describe the bug**

It seems, that for an "xs:gYearMonth" the generated PHP code has a wrong type hint.
This eventually leads to an type hint exception "Cannot assign string to property of type ?int".

**To Reproduce**

The given XSD looks like this:

~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="AwaitCorrectionFromCompanyType">
        <xs:sequence>
            <xs:element name="ValidAsOf" type="xs:gYearMonth">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
~~~

The corresponding generated PHP code looks like this:

~~~php
<?php

class AwaitCorrectionFromCompanyType extends AbstractStructBase
{
    /**
     * The ValidAsOf
     * @var int|null
     */
    protected ?int $ValidAsOf = null;

    /**
     * Constructor method for AwaitCorrectionFromCompanyType
     * @param int $validAsOf
     */
    public function __construct(?int $validAsOf = null)
    {
        $this
            ->setValidAsOf($validAsOf);
    }

    /**
     * Get ValidAsOf value
     * @return int|null
     */
    public function getValidAsOf(): ?int
    {
        return $this->ValidAsOf;
    }

    /**
     * Set ValidAsOf value
     * @param int $validAsOf
     */
    public function setValidAsOf(?int $validAsOf = null): self
    {
        // validation for constraint: int
        if (!is_null($validAsOf) && !(is_int($validAsOf) || ctype_digit($validAsOf))) {
            throw new InvalidArgumentException(sprintf('Invalid value %s, please provide an integer value, %s given', var_export($validAsOf, true), gettype($validAsOf)), __LINE__);
        }
        $this->ValidAsOf = $validAsOf;

        return $this;
    }
}
~~~ 

The given XML data looks like this:

~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<AwaitCorrectionFromCompany>
    <ValidAsOf>1997-02+01:00</ValidAsOf>
</AwaitCorrectionFromCompany>
~~~ 

Which leads to a PHP exception "Cannot assign string to property of type ?int".

**Expected behavior**

My understanding is that the generated PHP type for a "xs:gYearMonth" must be a string.

**Comment by mikaelcom** [comment]
Types are currently configured within this file: [xsd_types.yml](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/resources/config/xsd_types.yml). Temporarily, you can use your own file passing the `xsd-types-path` option. If you succeed to generate a fully functional package, hopefully, without further type issue, please share it with me so I can fix the default types.

**Comment by tbreuss** [comment]
I'll do it the way you suggested.

**Comment by tbreuss** [comment]
Please see pull request #293.

**Comment by tbreuss** [comment]
Pull request #293 fixes gYearMonth and gMonthDay.
