### ISSUE TITLE
Undefined constant "WsdlToPhp\PackageGenerator\Generator\SOAP_1_1"

### ISSUE THREAD

**Issue by DiDebru** [WsdlToPhp/PackageGenerator#298]
**Describe the bug**
Downloaded the phar and hit this error:
PHP Fatal error:  Uncaught Error: Undefined constant "WsdlToPhp\PackageGenerator\Generator\SOAP_1_1" in phar:///path/to//wsdltophp/src/Generator/GeneratorSoapClient.php:22

**To Reproduce**
Download the phar and use it.

**Expected behavior**
No fatal error.

**Additional context**

**Comment by mikaeldelsol** [comment]
Hi, so weird it did not break nor anyone else did encounter this issue before.
To be sure, can you precise your PHP version?
Thanks

**Comment by ZanMaticPratnemer** [comment]
I encountered the same problem with PHP 8.2.7
