### ISSUE TITLE
Symfony 7

### ISSUE THREAD

**Issue by datWeazel** [WsdlToPhp/PackageGenerator#308]
**Is your feature request related to a problem? Please describe.**
Currently, the library can't be used in Symfony 7 projects because it requires symfony/console and symfony/yaml to be at version 4.x, 5.x, or 6.x

**Describe the solution you'd like**
If I'm not mistaken it should be enough to update the required versions of the two packages since there weren't any breaking changes that I know of in any of those packages.

**Comment by AlexKratky** [comment]
https://github.com/WsdlToPhp/PackageGenerator/pull/309

**Comment by datWeazel** [comment]
PR #309 got merged so this can be closed. :)
