### ISSUE TITLE
SOAP attachments

### ISSUE THREAD

**Issue by KDederichs** [WsdlToPhp/PackageGenerator#311]
**Is your feature request related to a problem? Please describe.**
I'm looking for a SOAP library that supports SOAP Attachments (https://www.w3.org/TR/SOAP-attachments/) for sending and receiving. 
I was wondering if this generator was able to handle those attachments.

**Describe the solution you'd like**
If it can handle it: Add some documentation on how to handle attachments.
If it can't: Add ability to add Attachments.

**Comment by mikaelcom** [comment]
Hi, I won't be able to work on this feature, sorry
