### ISSUE TITLE
__Construct set methods call and enum value conflict

### ISSUE THREAD

**Issue by B-Gio-KGJ** [WsdlToPhp/PackageGenerator#35]
Hello,

I use the last version of PackageGenerator to re-build source of wsdl definitions. (first generation in past may).

I see the are a lot of differences since last version i used, including an error cause by valueIsValid() in set functions of enum objects.

When i instancy object, i set no property in declaration ( $foo = myObject(); ) then, i set properties with setProperty() functions after.

by default, __construct method call set methods of each object with null value but valueIsValid function not expect null value, just corrects values/object returned by getValidValues.

![capture d ecran 2015-09-14 a 18 11 12](https://cloud.githubusercontent.com/assets/5663281/9871189/24cc4fb8-5b92-11e5-9793-ac7d0d2123ad.png)

![capture d ecran 2015-09-14 a 18 10 41](https://cloud.githubusercontent.com/assets/5663281/9871192/2adb660a-5b92-11e5-86d6-35e996581238.png)

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Value "" is invalid, please use one of: Pound, Kilogram, Tonnes' in /[PATH]/src/Struct/Weight.php:66

Can you add an option in the generator to add null value as valid in getValidValues() array returned ?

Regards,

**Comment by mikaelcom** [comment]
Indeed, it can be frustrating to have to always pass the Enum's value for a constructor especially if this type of parameter is the last one of the a long list.

**Comment by B-Gio-KGJ** [comment]
Very reactive !

Thanks for that, it's work perfectly !
