### ISSUE TITLE
Objects at different levels with same name, get merged

### ISSUE THREAD

**Issue by judgej** [WsdlToPhp/PackageGenerator#38]
Now, I'm not sure if this is a problem with the API I'm trying to connect to, or a problem in this library. I suspect there may be a bit of each. Straight in, here is the WSDL:

http://partners.rowebooks.co.uk/test/OrderService.svc?wsdl

Here is the schema, where I think the problems start:

http://partners.rowebooks.co.uk/test/OrderService.svc?xsd=xsd0

Notice that there is an outer element `order` with some fields including `orders`. Now `orders` is optional - 0 or 1 occurrences. According to the customer's spec, it should be 1 or more (unbounded), so I suspect something is wrong in there.

Inside `orders` is another optional object called `order`. That has the same name as the top-level wrapper, but different fields. When I generate code using this library, both of these `order` objects get merged into one (`StructType\Order`) with all the fields merged together. Should these not be two separate objects, perhaps `Order` and `OrdersOrder` or something?

I can get it to kind of work by creating `$order_inner` and `$order_wrapper`, setting different fields and leaving the rest blank, but the inner `order` does not seem to recognise the array of `Detail` objects I give it - it does not complain, but they don't get included in the XML that is sent.

Apologies if I'm not using the right lingo - just take my "objects" and "fields" as a flexible lump of data :-)

**Comment by mikaelcom** [comment]
In my opinion, `order` should not be used twice to define two different structs otherwise it's confusing even for a human, don't you think?

In any case, PHP won't be able to map the right class to its corresponding XML as the `classmap` allows to define PHP class using a key. The key has to be the name of the struct. So if two structs use the same name, you can't define two array entries with the same key.

I don't see how I could get around this issue. If you have any proposal, feel free to let me know.

Good luck;

**Comment by judgej** [comment]
This is what SoapUI gives me for a test message:

~~~xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <ImportOrder>
         <!--Optional:-->
         <order>
            <!--Optional:-->
            <sentDate></sentDate>
            <!--Optional:-->
            <companycode></companycode>
            <xmlversion>1.1</xmlversion>
            <!--Optional:-->
            <email></email>
            <!--Optional:-->
            <orderFor></orderFor>
            <!--Optional:-->
            <orders>
               <!--Optional:-->
               <order>
                  <!--Optional:-->
                  <customerref></customerref>
                  <!--Optional:-->
                  <InvoiceFile></InvoiceFile>
                  <!--Optional:-->
                  <shippingMethod></shippingMethod>
                  <!--Zero or more repetitions:-->
                  <Contact ID="1" companyName="Acme" AttentionTo="Fred" address1="Norham Road" extendedAddress="" city="Whitley" postCode="NE999ZZ" state="" county="" countryCode="GB" phone="" email="test@example.co.uk">?</Contact>
                  <!--Optional:-->
                  <details>
                     <!--Zero or more repetitions:-->
                     <detail ID="123" isbn="ISBN1234" title="Book Title" qty="1">Something</detail>
                  </details>
               </order>
            </orders>
         </order>
      </ImportOrder>
   </soapenv:Body>
</soapenv:Envelope>
~~~

That submits to the API and I get a successful response. It does not mean the data is valid (the data is processed later) but the XML message is structured correctly. You can see the two `order` objects in there, with different data, but SoapUI does not split the SOAP message down into nested and repeated objects like your library - it just gives me a lump of XML to play with.

So - is this SOAP WSDL rubbish? Should the supplier have avoided using `order` twice, nesting them like this? Or is that perfectly valid, and it is this library that should treat them as separate objects? Or is the merged/combined object fine for this purpose (luckily with no parameters with the same name but different data types)?

**Comment by judgej** [comment]
Thanks - that was my suspicion, that the API was doing a crazy thing. They have a FTP API I can use, dropping XML files into their FTP area, and polling it for response XML files. Not ideal, but it should work.

**Comment by mikaelcom** [comment]
SOAPui indeed does not care of the name but does care about the structure. So it basically generateds a XML structure based on the WSDL so having two XML element with the same name is valid.

On the other hand, as you know, you can't have two classes with the same name in the same namespace. In addition, this case is very specific as we would have to test if the current element is contained by an element of the same name knowing that the child element can be in a deep structure. I don't think this case will be handled and can be handled, sorry.

**Comment by judgej** [comment]
Thanks for your time in looking at this :-)

**Comment by judgej** [comment]
Ping @bradydan for info.
