### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by rossedman** [WsdlToPhp/PackageGenerator#39]
This isn't an issue but thank you for building this. Finding this package really saved me a lot of time and helped me understand SOAP in PHP more than any other resource on the internet. Also, really cool seeing a package use box project.

Once again, thanks.

**Comment by mikaelcom** [comment]
Thank you to you for giving such a feedback, really appreciate it! :smile:

**Comment by ceeram** [comment]
This can be closed as won't fix :) cant fix awesomeness.
Op 9 dec. 2015 21:47 schreef "Mikaël DELSOL" <notifications@github.com>:

**Comment by mikaelcom** [comment]
ok ok, I wanted to enjoy it a little while :blush:

**Comment by rossedman** [comment]
@ceeram @mikaelcom Have to give credit where credit is due. Sometimes I stumble across these projects and I'm like "I would love to contribute to that!" and then I think "it already works so good, what do I do?". Haha.

**Comment by mikaelcom** [comment]
I'm not currently working with SOAP web services but for those who do, this is for anyone who's reading this, do not hesitate to propose/submit improvements to both the [PackageGenerator](https://github.com/WsdlToPhp/PackageGenerator) and the classes provided by the [PackageBase](https://github.com/WsdlToPhp/PackageBase) project. Here is how anyone can contribute too :wink: 

Thx again :smile:

**Comment by rossedman** [comment]
@mikaelcom I will be using it quite a bit over the next couple weeks, so if I find anything I'll generate a PR. Thanks!
