### ISSUE TITLE
Support for several services under one provider and several providers

### ISSUE THREAD

**Issue by GroxExMachine** [WsdlToPhp/PackageGenerator#42]
In my project I have several services from one provider, so the below is proposed structure.
It will be good, if generator will support it.

/src/Services/Provider1
* AdGroups (own wsdl)
 * ArrayType
 * EnumType
 * ServiceType
 * StructType
* Campaigns (own wsdl)
 * ArrayType
 * EnumType
 * ServiceType
 * StructType

/src/Services/Provider2
* AdGroups (own wsdl)
 * ArrayType
 * EnumType
 * ServiceType
 * StructType
* Campaigns (own wsdl)
 * ArrayType
 * EnumType
 * ServiceType
 * StructType

**Comment by mikaelcom** [comment]
Currently you are able to have such a hierarchy if each provider's service has its own WSDL (/src/Services/Provider1/ and /src/Services/Provider2/ are your existing main directory), am I wrong?

* /src/Services/
    * Provider1/
        * AdGroups/ (own wsdl)
            * src/
                * ArrayType/
                * EnumType/
                * ServiceType/
                * StructType/
                * composer.json
        * Campaigns/ (own wsdl)
            * src/
                * ArrayType/
                * EnumType/
                * ServiceType/
                * StructType/
                * composer.json
    * Provider2/
        * AdGroups/ (own wsdl)
            * src/
                * ArrayType/
                * EnumType/
                * ServiceType/
                * StructType/
                * composer.json
        * Campaigns/ (own wsdl)
            * src/
                * ArrayType/
                * EnumType/
                * ServiceType/
                * StructType/
                * composer.json

So I don't see what you would like to do actually, could you precise more please?

**Comment by GroxExMachine** [comment]
Yes, the proper structure of folders can be generated.
**First**, you need to setup --namespace="Provider1\Campaigns" 
**Second**, you need to update the composer.json of your project with proper paths
```json
    "autoload": {
        "psr-4": {
          "Provider1\\Campaigns\\": "./Provider1/AdGroups/src/",
          "Provider1\\Campaigns\\": "./Provider1/Campaigns/src/",
          "Provider2\\Campaigns\\": "./Provider2/AdGroups/src/",
          "Provider2\\Campaigns\\": "./Provider2/Campaigns/src/",
        }
     }
```
**Third**, you need to run _composer dump-autoload_ to update autoloader.

This issue can be closed, and I suggest to add this info to manual.

**Comment by mikaelcom** [comment]
I think it's more about [FAQ](https://github.com/WsdlToPhp/PackageGenerator/wiki/FAQ), don't you think ?

Plus, I think the readme is already long enough.

**Comment by GroxExMachine** [comment]
Agree absolutly.

**Comment by mikaelcom** [comment]
Done : https://github.com/WsdlToPhp/PackageGenerator/wiki/FAQ#how-to-have-several-packages-under-the-same-directory-and-common-namespaces. You tell me if you think this is not clear
