### ISSUE TITLE
Constant naming separate with underscore

### ISSUE THREAD

**Issue by GroxExMachine** [WsdlToPhp/PackageGenerator#44]
Now _StartDate_ become _VALUE_STARTDATE_ 
I suggest it become _VALUE_START_DATE_. To separate words with underscore.

**Comment by mikaelcom** [comment]
Do we agree on these cases?
- Microsoft_IIS => MICROSOFT_IIS
- 0Value => 0_VALUE
- 0value => 0_VALUE
- CamelCase => CAMEL_CASE
- camelCase => CAMEL_CASE
- Value0Ok => VALUE_0_OK
- value0ok => VALUE_0_OK
- valueOk0 => VALUE_OK_0
- _other cases ?_

If yes and if you're good at regexp, do you think a regexp could ease the `preg_split` of these strings?

I started some tests but failed ... :(

thx

**Comment by GroxExMachine** [comment]
I added some cases.
This regexp matches all /([A-Z]+[a-z]*)|([a-z]+)|(\d)+/
Here it can be checked: http://regexr.com/3cpb7

- Microsoft_IIS
- 0Value
- 0value
- CamelCase
- CamelCase00
- camelCase
- Value0Ok
- value0ok
- value01ok
- 15value01ok
- Rirght15value01ok
- valueOk0

I may look what  to do next later.

**Comment by mikaelcom** [comment]
indeed, I did not know this tool, it's very good :smile: 

I modified the replace pattern to `_$1_$2_$3_` so `0Value` becomes `___0__Value___` too, then I'll only have to:
- remove any _ at the beginning and at the end
- replace multiple _ to only one _

Any additional thought?

Thx

**Comment by GroxExMachine** [comment]
I updated replacement to: $&_
It is giving us:
- Microsoft__IIS_
- 0_Value_
- 0_value_
- Camel_Case_
- Camel_Case_00_
- camel_Case_
- Value_0_Ok_
- value_0_ok_
- value_01_ok_
- 15_value_01_ok_
- Rirght_15_value_01_ok_
- value_Ok_0_

It is simplier and looks better
So, you need to 
- remove trailing underscore 
- replace multiple _ to only one _

**Comment by mikaelcom** [comment]
I'm impressed! I'll integrate it later.

**Comment by mikaelcom** [comment]
I has to use [$1$2$3_](https://github.com/WsdlToPhp/PackageGenerator/commit/ab372fd989f33ea2dd59976ada2148f7f4327111#diff-eed8bf7a09cef4aec3dd8475c63ea0a8R20) instead of `$&_` as it seemed to not work with PHP. Did I miss something?

I added you as [contributor](https://github.com/WsdlToPhp/PackageGenerator/commit/f5c92aa9417005a0aa8e95b68aa3c3fd80aeeee9#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R26), is it ok with you? Do want me to add an email?

**Comment by GroxExMachine** [comment]
I first time saw this $& symbol on that site instead of $1, so, I assume it can be not implemented in PHP.

I am very glad for your decision, please add this email: grox@mail.ru
