### ISSUE TITLE
Reserved PHP-Keywords in Class Names

### ISSUE THREAD

**Issue by jzaeske** [WsdlToPhp/PackageGenerator#45]
I've found a problem relating to reserved PHP Keywords.

We are using a WSDL containg the following section
```
<wsdl:operation name="doBankTransferAuth" parameterOrder="in0 in1 in2">
    <wsdl:input message="impl:doBankTransferAuthRequest" name="doBankTransferAuthRequest"/>
    <wsdl:output message="impl:doBankTransferAuthResponse" name="doBankTransferAuthResponse"/>
</wsdl:operation>
```
which results in a ServiceClass `class Do`. Due to the case-**insensitivity** of reserved PHP-Keywords, this is an syntax error in the generated class (up to now, I wasn't aware of this problem neither). 

I've analyzed the problem and found out 2 things, that may lead to this problem:

1. `\WsdlToPhp\PackageGenerator\ConfigurationReader\ReservedKeywords` does a case sensitive keyword check, so non-lowercase occurrences of the filtered keywords are not detected.
2. It seems like `\WsdlToPhp\PackageGenerator\ConfigurationReader\ReservedKeywords` is only used to check the the name inside the WSDL (in this case `doBankTransferAuth`) but not the derived Classname `Do`.

A quick fix to avoid this problem is generating the classes with an static prefix or suffix, but we like to avoid this.
If desired, I would offer to provide a pull request for this.

**Comment by mikaelcom** [comment]
Hi,
I see what you're talking about, please make your PR on the **[feature/issue-45](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-45)** branch.
We'll discuss on your way to implement it. Please provide unit tests too.
Good luck,
Thx
