### ISSUE TITLE
Error while passing array parameter

### ISSUE THREAD

**Issue by cloudelabs** [WsdlToPhp/PackageGenerator#51]
After successfully generating package and trying to send a request I get this error

> Catchable fatal error: Argument 1 passed to StructType\LogonRequest::__construct() must be an instance of StructType\LogonRequestData, array given

**Code**

`if ($logon->Logon(new \StructType\LogonRequest($params)) !== false) {`

**Comment by mikaelcom** [comment]
Does it mean you pass `$params` as an array?
Could you send me over the WSDL at contact@wsdltophp.com?

Thx

**Comment by cloudelabs** [comment]
Yes $params is an array.

```
$params = array('AgentName'=>'AGTNAME', 'Password'=>'PASSWORD', 'RoleCOde'=>'APIB', 'DomainCode'=>'WWW');
 
if ($logon->Logon(new \StructType\LogonRequest()) !== false) {
    print_r($logon->getResult());
} else {
    print_r($logon->getLastError());
}
```


The WSDL can be opened only from IP that is white listed by the API provider

**Comment by mikaelcom** [comment]
OK you created an array but you have to know that you don't have to use array anymore, unless it's explicitely required by the type of the parameters.

You must use a \StructType\LogonRequestData object as `$params` that contains the values you're trying to send using an array. The generated package contain all the classes, everything is OOP ;),

let me know,

**Comment by GroxExMachine** [comment]
I assume, you need to use it like this:
```php
$LogonRequestData = new StructType\LogonRequestData();
$LogonRequestData->setAgentName('AGTNAME');
$LogonRequestData->setPassword('PASSWORD');
...

$LogonRequest = new \StructType\LogonRequest();
$LogonRequest->setLogonRequestData($LogonRequestData);

$logon->Logon($LogonRequest);
```

**Comment by cloudelabs** [comment]
Perfect! However I still face issue in setting header.

> Catchable fatal error: Argument 1 passed to ServiceType\Logon::setSoapHeaderContractVersion() must be an instance of ServiceType\int, integer given

I also tried `$ContractVersion = (int) 340` still no luck

```
$logon = new \ServiceType\Logon($options);
$ContractVersion = 340;    // Problem here
$logon->setSoapHeaderContractVersion($ContractVersion);

$LogonRequestData = new StructType\LogonRequestData();
$LogonRequestData->setAgentName('AGTNAME');
$LogonRequestData->setPassword('PASSWORD');
$LogonRequestData->setRoleCOde('APIB');
$LogonRequestData->setDomainCode('WWW');

$LogonRequest = new \StructType\LogonRequest();
$LogonRequest->setLogonRequestData($LogonRequestData);

$logon->Logon($LogonRequest);
print_r($logon->getLastResponse());
```

**Comment by mikaelcom** [comment]
Then there is maybe a remaining bug in there on detecting the type hint of the parameter.

Could you paste the `\ServiceType\Logon::setSoapHeaderContractVersion` method signature with the doc block associated to it?

Thx

**Comment by cloudelabs** [comment]
Here you go,

```
/**
     * Sets the ContractVersion SoapHeader param
     * @uses AbstractSoapClientBase::setSoapHeader()
     * @param int $contractVersion
     * @param string $nameSpace
     * @param bool $mustUnderstand
     * @param string $actor
     * @return bool
     */
    public function setSoapHeaderContractVersion(int $contractVersion, $nameSpace = 'http://schemas.navitaire.com/WebServices', $mustUnderstand = false, $actor = null)
    {
        return $this->setSoapHeader($nameSpace, 'ContractVersion', $contractVersion, $mustUnderstand, $actor);
    }
```

**Comment by GroxExMachine** [comment]
@cloudelabs could you please download WSDL file and send it to @mikaelcom to contact@wsdltophp.com ?

**Comment by mikaelcom** [comment]
@GroxExMachine no need, I'll make a fix on the hotfix branch (without testing it with real data, bad :P) so @cloudelabs will have to test to test the generator on this branch

**Comment by cloudelabs** [comment]
Ok. I am new to Github and not familiar with the terms 'branch' and 'hotfix'. Just guide me so that I can work it out

**Comment by mikaelcom** [comment]
Ok, I'll do :wink:

**Comment by mikaelcom** [comment]
@cloudelabs could you try using this phar? thx
[wsdltophp.phar.zip](https://github.com/WsdlToPhp/PackageGenerator/files/154510/wsdltophp.phar.zip)

**Comment by cloudelabs** [comment]
How do I use this :o

**Comment by mikaelcom** [comment]
How did you use the generator at first?

**Comment by cloudelabs** [comment]
Ok got it.

**Comment by mikaelcom** [comment]
any progress ? thx

**Comment by cloudelabs** [comment]
Works! But it would be quite easy to build an array and pass it as a parameter to any request. I have lot of loops to go through to build a huge request for AirLine booking.

**Comment by mikaelcom** [comment]
IMHO array are old fashionned but if you prefer array then you can use the public static [__set_state](https://github.com/WsdlToPhp/PackageBase#usage) method present in every generated Struct classes.
It accepts an unique array as parameter with the keys as the class property (same case) and the value so you dont have to set every parameter. Nevertheless be careful if the struct has required parameters, the tt might fail as it instanciates the class with the default values. In the case of a required parameter, the construct class does not define a default value (null) so it will fail

Thx for your patience and your validation,
