### ISSUE TITLE
Naming. Class _Add and method _add_1/2/3... names. Need to minify reserved_keywords.yml

### ISSUE THREAD

**Issue by GroxExMachine** [WsdlToPhp/PackageGenerator#54]
```php
class _Add extends AbstractSoapClientBase

public function _add_3(\AppBundle\Provider\YandexDirect\Campaigns\StructType\AddRequest $parameters)

* Method to call the operation originally named add
```
I found this changes and this https://github.com/WsdlToPhp/PackageGenerator/pull/46
But I did not understand, why do we need this?

class Add and method add() works well. I checked it. Such as many other words in reserved_keywords.yml that can be used as class name, like the First.

// PHP 5.6

**Comment by mikaelcom** [comment]
If you look from the line [150](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/resources/config/reserved_keywords.yml#L150) in the reserved_keywords.yml, you can see that the methods are defined in the parent classes, this is why these methods are marked as reserved.

This is not perfect/good as:
- this does not take into account the class that is being generated. Indeed :
    - the **ServiceType** classes that inherit from **AbstractSoapClientBase** should only not override the methods defined by this class
    - the **StructType** classes that inherit from **AbstractStructBase** should only not override the methods defined by this class
    - the **ArrayType** classes that inherit from **AbstractStructArrayBase** should only not override the methods defined by this class
- if the parent classes are not from WsdlToPhp\PackageBase, the parent's methods are not the same (only from the WsdlToPhp\PackageBase's interfaces)
- the methods should not be taken into account to define the class name but just for the methods. The PHP reserved keywords MUST be taken into account both for the class name and the method names

Is it enough clear? Am I fully right?

This is clearly something that needs to be improved, I hope you're not in the hurry as I don't know when it will be improved,

**Comment by GroxExMachine** [comment]
> This is clearly something that needs to be improved, I hope you're not in the hurry as I don't know when it will be improved,

This projeсt very useful in it current state. The naming is just a step to perfectness, so it can wait. IDE gives me autocomplete anyway. Oh. Yes, not when it is about fabrics. So, it can be issue, but not right now.

**Comment by GroxExMachine** [comment]
> Is it enough clear? Am I fully right?

I will study it and answer later.
