### ISSUE TITLE
xsd:long is "int" in validation rules - error with values that not fit

### ISSUE THREAD

**Issue by GroxExMachine** [WsdlToPhp/PackageGenerator#55]
I was forced to turn off validation to avoid errors with values, that already bigger than 32bit integer.
And this is a question, what to do on different platforms - 32bit and 64 bit.

**Comment by mikaelcom** [comment]
@GroxExMachine Do you think of another better solution than I found?

**Comment by GroxExMachine** [comment]
@mikaelcom I think, that this is a simple(in terms of realization) and good solution.

**Comment by mikaelcom** [comment]
solved in [2.0.1](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.0.1) and [1.5.1](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/1.5.1)
