### ISSUE TITLE
Set options in constructor?

### ISSUE THREAD

**Issue by FatherShawn** [WsdlToPhp/PackageGenerator#62]
I have this generated class:
`class Service extends AbstractSoapClientBase`

The tutorial code calls for setting options on each call.  Is there a reason not to add a constructor to Service:
```php
  public function __construct(array $wsdlOptions = array(), $resetSoapClient = true) {
    $defaults = array(
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_URL => 'https://path/myframework.asmx?wsdl',
      \WsdlToPhp\PackageBase\AbstractSoapClientBase::WSDL_CLASSMAP => \path\to\Soap\Orders\ClassMap::get(),
    );
    $wsdlOptions = array_merge($defaults, $wsdlOptions);
    parent::__construct($wsdlOptions, $resetSoapClient);
  }
```

**Comment by mikaelcom** [comment]
I'm not a big fan of such duplicated code as if you have dozens of Service classes, you'll have dozens of places where you'll have to change the default options. In addition, for me, the options are variables meaning that the WSDL could be changed whereas the code would be still working (dev and prod environment for example).

I understand your point but maybe it would then be good to create a class that takes care of instanciating the Service class you need with the common options:

```php
use WsdlToPhp\PackageBase\AbstractSoapClientBase;

class Service
{
    private static $options = array(
        AbstractSoapClientBase::WSDL_URL => 'https://path/myframework.asmx?wsdl',
        AbstractSoapClientBase::WSDL_CLASSMAP => \path\to\Soap\Orders\ClassMap::get(),
    );
    /**
     * Ideally we should use singleton
     */
    public static function getServiceCreate($resetSoapClient = true, array $options = array())
    {
        return new ServiceType\Create(array_merge(self::$options, $options), $resetSoapClient);
    }
}
```

My other advice would be to:
- create a class that extends the `AbstractSoapClientBase` class,
- override the constructor in the new class as you did,
- generate the package by using the `--soapclient` option specifying your own class.

What do you think?

**Comment by FatherShawn** [comment]
First off, I think I should think longer before posting an issue, especially on Friday afternoons!

I was reacting to the tutorial code, which of course is very minimal, and thinking, "I don't want to hard code that endpoint everywhere I intend to use this!" Especially since the particular endpoints I'm working with only generate one Service class each.  Like you I don't want to change a value in dozens of lines of code.

Of course I have a configuration system, and today I'm thinking a factory class that leverages that configuration system to return the service, especially since I also have a service system, so I can reuse that instantiation.

Thanks for the ready response and prodding me to get up to architectural altitude. :-)

**Comment by FatherShawn** [comment]
Another "Don't Repeat Yourself" question...  The library generated 18 implementations of _AbstractStructBase_ that extend another implementation of _AbstractStructBase_ - all of them are have names that begin _WSArgOf_ however, there are a larger number of other Structs that also extend that base class. The 18 subclasses would all benefit to having some configuration set at instantiation.  But I only see the option to use one custom class for Structs in your configuration.

> --struct (default: \WsdlToPhp\PackageBase\AbstractStructBase): sets the class from which StructType classes inherit, see StructInterface

Am I also not catching something here about how your generator works?  If not, perhaps I'll think about a strategy to instantiate these as well.  

I want future maintainers of this code to be able to regenerate this code if the third-party service changes without having to then rewrite a bunch of code.

Thank you for offering and maintaining this package.  Your open source commitment is a real gift!

**Comment by mikaelcom** [comment]
Structs classes are one type of class and currently can only extend one class. If I understand well, you would need to be able to extend a different class depending on the struct:
- if the struct has no parent class from the generated classes, use one class
- if the struct has a parent class from the generated classes, use another one class

Is this it?

> --struct (default: \WsdlToPhp\PackageBase\AbstractStructBase): sets the class from which StructType classes inherit, see StructInterface

This means that you can create your own class (that should implement at least implement the `StructInterface` interface or extend the `\WsdlToPhp\PackageBase\AbstractStructBase` (so you ensure the generated classes work well). Then you can implement your own features/behavior in your proper class.

Feel free to get back to me, if I can improve again the generator... :wink:

**Comment by FatherShawn** [comment]
Great, thanks!
