### ISSUE TITLE
base64Binary in Generated Classes

### ISSUE THREAD

**Issue by FatherShawn** [WsdlToPhp/PackageGenerator#63]
I have the following in the wsdl I'm dealing with:

```
<s:element name="AddFile">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="auth" type="tns:Authorization" />
            <s:element minOccurs="1" maxOccurs="1" name="productId" type="s:int" />
            <s:element minOccurs="0" maxOccurs="1" name="fileName" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="data" type="s:base64Binary" />
          </s:sequence>
        </s:complexType>
      </s:element>
```

Which results in the following `__construct()` signature:

```
public function __construct($productId = null, \Drupal\hol_goodway\Soap\Product\StructType\Authorization $auth = null, $fileName = null, base64Binary $data = null)
```

And base64Binary is undefined.  Searching through this repo and looking at some test files, should a StructType have been generated for base64Binary?  Am I missing a config setting?

**Comment by FatherShawn** [comment]
Rewriting the relevant references to use string instead made for successful submissions to SOAP. I'm happy to offer a contribution if you point me in the right direction.

**Comment by mikaelcom** [comment]
Sorry for my non response, the [xsd_type.yml](https://github.com/WsdlToPhp/PackageGenerator/blob/develop/src/resources/config/xsd_types.yml) is responsible for mapping XSD types to PHP types. In the case of an unknown type, the XSD type is used (which is not perfect I must admit). Ideally, the default type should be a `string`.

So feel free to add the `base64Binary` type alphabetically in the file and its associated PHP type. Then provide a test according to the update.

Finally make a pull request on the soon-to-be-created feature/63 branch.

Thx

**Comment by FatherShawn** [comment]
why does `src/resources/config/xsd_types.yml` differ from `tests/resources/xsd_types.yml`?  Does the new type need to occur in both?

As to testing, are you just looking for a method call in `tests/ConfigurationReader/XsdTypesTest.php` to verify the proper php type is returned or something more?

**Comment by mikaelcom** [comment]
The goal is to be able to have different types in test that those that are really used (even if there is currently no addionnal type). Ideally yes, copy the type in both files.

Concerning the test, do as you wish. There is not many tests in the XsdTypesTest.php class so you can add one for the new type if you wish to ensure it behaves as expected when calling `isXsd` and `phpType`.
