### ISSUE TITLE
Windows not able to run composer due to missing CA Certificate File

### ISSUE THREAD

**Issue by faithfulman18** [WsdlToPhp/PackageGenerator#67]
Issues:
On a Windows server it appears that it is unable to run the command using the PHAR file without errors due to the fact that composer is looking for a CA certificate file.  There isn't an obvious way of getting around this and still using the tool.  What would be helpful since this is a problem, is to allow users to disable the need for this process to run over tls.  And infact there is a way to do this in the composers config file, but since it is embedded in the PHAR file, you cannot edit it.  I have found that a work around is running the process and letting it fail.  Once that happens, it generates the composer.json file and you can edit it as I have below and it will take those settings that one time.  However, this is only a work around as you would have to do this each time, since when the process is finished the composer.json file is overwritten back to defaults.  But it does work for that one time.  

Request:  
It would be great if there was an option in the generate command to modify what gets added into the composer.json file somehow, so that you could pass in the disable-tls flag as "true".  This would fix the issue.

Here is a snippit with the corrected composer.json to allow the process to not need to check the CA Certificate.

“description”: “….”
**_"config": {
                 "disable-tls": true
               },_**
"require": {
        "php": ">=5.3.3",
        "ext-soap": "*",
        "wsdltophp/packagebase": "dev-master"
    },

**Comment by mikaelcom** [comment]
@faithfulman18 are you able to try the generation with this branch, [feature/issue-67](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/issue-67)? Using the new option named `composer-settings` with the value `config.disable-tls:true` such as:

`php console generate:package --urlorpath="**" --destination="**" --composer-name="**" --composer-settings="config.disable-tls:true"`

let me know how it works,
thx

**Comment by mikaelcom** [comment]
fixed in [1.9.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/1.9.0) and [2.4.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.4.0)
