### ISSUE TITLE
Installation via composer

### ISSUE THREAD

**Issue by Gemorroj** [WsdlToPhp/PackageGenerator#68]
I think in any case you should not use "dev-master", and specify stable versions.
![composer-problem](https://cloud.githubusercontent.com/assets/885731/20797380/91fbd05c-b7eb-11e6-9243-8d11e0e1a9bc.png)

**Comment by mikaelcom** [comment]
Too lazy to update the version each time (once a year....) it is necessary, I'll improve it

**Comment by mikaelcom** [comment]
You should be able to do a `composer update` in order to get the latest version with your pull request

**Comment by Gemorroj** [comment]
Yes, with the updated `composer.json` package succesfull installed.
