### ISSUE TITLE
PHP warning on str_repeat()

### ISSUE THREAD

**Issue by jpaljasma** [WsdlToPhp/PackageGenerator#7]
Few PHP warnings pop up when I run `console wsdltophp:generate:package -h`

after line output 
`  -wsdl-prox-lo, --wsdl-proxy-login[=WSDL-PROXY-LOGIN] Use proxy login`

I see
`PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in /Users/jaan/Sites/PackageGenerator/vendor/symfony/console/Descriptor/TextDescriptor.php on line 82`

PHP version:
`php -v`
`PHP 5.5.20 (cli) (built: Feb 25 2015 23:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies`

**Comment by mikaelcom** [comment]
I have opened an issue on symfony symfony/symfony#15105 because I don't see for the moment why we have this type of warning

**Comment by mikaelcom** [comment]
fixed in version 0.0.3
