### ISSUE TITLE
How to obtain a copy AbstractStructBase after the service call?

### ISSUE THREAD

**Issue by Gemorroj** [WsdlToPhp/PackageGenerator#71]
Example in readme:
```php
$serviceGet = new \MyPackage\ServiceType\MyPackageServiceGet($options);
$result = $serviceGet->getList();
```
I thought that the result will be an object AbstractStructBase. But i have stdClass object.
In the code I see that the result is created like the code:
```php
$this->setResult(self::getSoapClient()->GetRequestList());
```
And it can't be an instance AbstractStructBase.
How can I obtain a copy of AbstractStructBase after the service call?

**Comment by mikaelcom** [comment]
If you get a stdClass, in my point of view there is three possibilities:

- the classmap option does not contain the type of the result, check the XML response,
- the classmap contains the type of the result but it is not mapped by the SoapClient (as this is what SoapClient does normally, no additional code is contained to do that), check any irregular caracters that could "break" the link
- the classmap contains the type of the result but the class namespace is not correct so the SoapClient does not succeed to find it, so it returns a stdClass

So check the two points and let me what you found.

**Comment by Gemorroj** [comment]
I'm sorry, I didn't write `AbstractSoapClientBase::WSDL_CLASSMAP => \MyPackage\MyPackageClassMap::get()`.
It would be good to have instructions for updating from "wsdltophp/wsdltophp" to "wsdltophp/packagegenerator".
