### ISSUE TITLE
Add Namespace support

### ISSUE THREAD

**Issue by Geabulek** [WsdlToPhp/PackageGenerator#8]
The structure of a package could be the following.

\\[_Package Name_]\
\\[_Package Name_]\Enum
\\[_Package Name_]\Service
\\[_Package Name_]\Struct

(actually, prefix could be replaced by namespace support).

**Comment by mikaelcom** [comment]
This is THE thing I wanted to introduce with the [feature/mandevilla](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/mandevilla) branch.

My first thought was to introduce a new option allowing to enable namespace and so the top level namespace(s) to use for each generated class.

But my second thought is that we should use namespace as soon as the PHP version allows it (pretty always as the project requires PHP=>5.3.3 (composer.json), **am I right ?**). We would then have, as you mentionned, something like this:
* {PackageName}/
    * Enum/
        * ColorValues.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Enum
        * SizeValues.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Enum
        * ...
    * Struct/
        * Color.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Struct
        * Size.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Struct
        * ...
    * Service/
        * Get.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Service
        * Add.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Service
        * ...

Nevertheless, do you agree that we would need an option to at least specify the top level namespace(s) to use to prefix the generated namespace : Enum, Struct, Service ? By default, it'll be empty.

Plus, classes can be generated using the name of the Structs/Operations. So we should also use namespace(s) in case the user wants something like this:
* {PackageName}/
    * Add/
        * StructAddProduct.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Add
        * ServiceAdd.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Add
    * Get/
        * StructGetProduct.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Get
        * ServiceGet.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Get
    * Items/
        * StructProductItems.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Items
        * StructColorItems.php
            * namespace = \{TopLevelNamespace\}\\{PackageName}\Items
    * ...

Am I missing something? Would it be ok this way?

**Comment by Geabulek** [comment]
Doc says namespace >=5.3.0 so I agree.

Assuming people use: PSR4 and composer, I can thing about 2 cases:
- the one where the package is directly a dependency (vendor/[_Vendor name_]/[_Package name_]/ with an autoload generated by composer
- the one where this package is used in some place of the project (say folder /src/Interface/blah blah/[_Package name_]/ )

My use case is a bit of both: I am building a library (project-agnostic) with a few web services (and the boiler-plate code to go with it) with I reused as a dependency in my projects. Sometimes project need one extra-field, which impacts the WSDL, which impacts the generated package. Namespace would allow me to overwrite package. 

As for the internal structure, you made the choice to generate standalone packages. As a user, I just consume this package and have no opinion regarding its internal composition. 

Nevertheless, I think you should consider moving all the generic code (I think about _Prefix__ WsdlClass) in different component which would be a dependency (quite easy with namespaces & composer). This would avoid having the same code duplicated as many times as there are interfaces (I have a dozain at my current project).

**Comment by mikaelcom** [comment]
If I sumup well your comment:
* There is no need for a top level namespace, at least the {PackageName} is sufficient
* The {PackageName}WsdlClass.php, {PackageName}Autoload.php could be externalized

As you seem to use pretty well the generator:
* Do you use the generated root files: Autoload, WsdlClass, ClassMap ?
* If you encountered the case, do you think Array structs (ArrayOfString => {PackageName}StructArrayOfString for example) should have their own directory as Enum ? We would have:
    * Array/
    * Enum/
    * Service/
    * Struct/
* If you're not using the WsdlClass, how to proceed to use you own SoapClient?


In any case, feel free to send me  your feedbacks at contact@wsdltophp.com,
thanks

**Comment by Geabulek** [comment]
> There is no need for a top level namespace, at least the {PackageName} is sufficient

Quite the opposite (but I deleted the comment while editing). I could need n top level namespace because according to [PSR-4](http://www.php-fig.org/psr/psr-4/) the folder structure would match the namespace imbrication.

> The {PackageName}WsdlClass.php, {PackageName}Autoload.php could be externalized

Some of it, yes I think. I know you inherit from WsdlClass almost everywhere but I didn't find the point for Enum and Struct. 

> Do you use the generated root files: Autoload, WsdlClass, ClassMap ?

Yes, I haven't tried to avoid them. With namespace, I would use composer classmap which I think would be better from a performance point of view. Autoload.php requires classes that I won't use in the end.

> If you're not using the WsdlClass, how to proceed to use you own SoapClient?

I used NuSoap but could not deal with additionnal namespaces, I use SoapClient but attributes are painful and manual classmapping was less appealing than WsdlTophp ;-)

**Comment by mikaelcom** [comment]
Indeed, you're right for the namespace!

The WsdlClass is sort of an utility class that provides useful methods, in my point of view and regarding the multi cases, to ease the access and the handling of multiple informations: XML request, headers, iterate through array of values and so on. As you proposed, we could have an external package that would be used by the generated package (using a dedicated composer.json file) that contains utility classes: SoapClient for Service classes, Structs utilities and so on.

For the Autoload, I haven't tried to see if, without having loaded the classes (mentionned by the classmap), the SoapClient populates the return object with a generated class. Have you ?

**Comment by Geabulek** [comment]
After a few test, I confirm I won't use autoload.
I add the following in composer.json
```json
{
    "autoload": {
        "classmap": [ "Acme/Package/directory/" ]
    }
}

```

and execute ```composer dumpautoload``` in order to generate classmap.

```require_once('../vendor/autoload.php'); ``` replaces ```require_once dirname(__FILE__) . '/PrefixAutoload.php' ``` 

NB: We need to disambiguate "classmap" : 
* composer classmap is an array that links classes to their folder for autoloading
* soap classmap is an array that links tag to classes.

When you say  
>For the Autoload, I haven't tried to see if, without having loaded the classes (mentionned by the classmap), the SoapClient populates the return object with a generated class. Have you ?

I still use Soap classmap from WsdlToPhp since it is the only known way to populate attributes.

**Comment by mikaelcom** [comment]
If you have some time to waste, I'll be glad if you can test the [feature/mandevilla](https://github.com/WsdlToPhp/PackageGenerator/tree/feature/mandevilla) branch as it now has namespace support and (non-)standalone mode.

Take a look to the README file as it has been updated,

Let me know how it works and feel free to create as much issue tickets as you need

**Comment by mikaelcom** [comment]
you can use the [first major release candidate](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/1.0.0rc01) from now

**Comment by mikaelcom** [comment]
namespace is now handled
