### ISSUE TITLE
better debug support

### ISSUE THREAD

**Issue by greggreenhaw** [WsdlToPhp/PackageGenerator#83]
Its failing with this error and It very difficult to track this down  
[InvalidArgumentException]
  Name "0" is invalid, please provide a valid name

**Comment by mikaelcom** [comment]
This error comes from the [PhpGenerator](https://github.com/WsdlToPhp/PhpGenerator) project which is used to generate the PHP files.

Nevertheless, it's true that it does allow to easeily know where this error comes from when generating a class.

I will create an issue to improve the [PhpGenerator](https://github.com/WsdlToPhp/PhpGenerator) project then I'll see if it can be improved into this PackageGenerator project.

**Comment by mikaelcom** [comment]
Release [1.11.1](https://github.com/WsdlToPhp/PackageGenerator/releases/download/1.11.1/wsdltophp-1.11.1.phar) and [2.6.1](https://github.com/WsdlToPhp/PackageGenerator/releases/download/2.6.1/wsdltophp-2.6.1.phar) phar files are up to date with the improvement made into the [PhpGenerator](https://github.com/WsdlToPhp/PhpGenerator) project.

If you fail generating your project, don't hesitate to send me the WSDL and your generating options so I can figure out where it comes from. This error is unusual.

**Comment by greggreenhaw** [comment]
The wsdl is from here it would be great if you could check it out
http://www.starstandard.org/images/SIGXMLSTAR5/STARSchemaRepository_Rev594.zip

path:
starschemas-5.9.4/STAR/5.9.4/WSDL/WS4Templates/ProcessServiceAppointment.wsdl

**Comment by mikaelcom** [comment]
Using the indicated WSDL, the package has been generated successfully using the latest generation version with this folder hierarchy by exporting your archive in the wsdl folder using the content of `starschemas-5.9.4\STAR\5.9.4` folder:
```
|-wsdl
    |-WSDL
        |-WS4Templates
            |-ProcessServiceAppointment.wsdl
```

And these options:
```
    --urlorpath="./wsdl/WSDL/WS4Templates/ProcessServiceAppointment.wsdl" \
    --destination="./" \
    --composer-name="process-service-appointment" \
    --force;
```

let me know if it works well too for you or if you still encounter issues
