### ISSUE TITLE
Major or Minor for next release?

### ISSUE THREAD

**Issue by mikaelcom** [WsdlToPhp/PackageGenerator#90]
**To all**: A new release is about to be created so I was wondering what choice would be the best between a Major and a Minor increment for the next release. I read the semver specification for [Major](http://semver.org/#spec-item-8) and [Minor](http://semver.org/#spec-item-7) increment so here's the facts:
- A new option will be added (soon): src-dirname. Default value would be `src`, allowing to provide a workaround for the comments on the issue https://github.com/WsdlToPhp/PackageGenerator/issues/25#issuecomment-291422117
- Base classes from [DomHandler](https://github.com/WsdlToPhp/PackageGenerator/tree/2.6.1/src/DomHandler) directory have been moved to an independent package and used as a [dependency](https://github.com/WsdlToPhp/PackageGenerator/issues/89). In addition, classes under the directory [DomHandler/Wsdl](https://github.com/WsdlToPhp/PackageGenerator/tree/2.6.1/src/DomHandler/Wsdl) have been moved to the root directory [WsdlHandler](https://github.com/WsdlToPhp/PackageGenerator/tree/develop/src/WsdlHandler).
- New validation rules have been added which will impact the already generated classes . See https://github.com/WsdlToPhp/PackageGenerator/issues/85 for classes that contain boolean properties, see https://github.com/WsdlToPhp/PackageGenerator/issues/86 for classes that contains properties with maxEclusive and minExclusive attributes
- Several issues have been implemented in order to improve and fix generated classes: https://github.com/WsdlToPhp/PackageGenerator/issues/84, https://github.com/WsdlToPhp/PackageGenerator/issues/82
- composer.json have been reviewwed to match older PHP version and newer PHP version, see https://github.com/WsdlToPhp/PackageGenerator/commit/f0947a5553ce6cb56d8db606c4604139700364b1

If no one inherits from the PackageGenerator project, then a Minor increment should suffice. Otherwise, I think it requires a Major increment.

The next release will be created based on the 2.* tag. Release 1.* version will not be maintained anymore as composer.json handles older and newer PHP version. Nevertheless, the phar file will be created for both PHP versions (PHP 5 and PHP 7). The next release tag could be:
- **2.7.0**: in this case a `composer update` will retrieve all the updates if you specified ^2.0 or ~2.0
- **3.0.0**: in this case a `composer update` will NOT retrieve all the updates if you specified ^2.0 or ~2.0, you will have to update your composer.json file in order to specify ^3.0

Any advice is good to take 😃

**Comment by Gemorroj** [comment]
I find no changes that break backward compatibility in the generated code. I would prefer a minor update.
So the update was less painful, it would be good to add `UPGRADE` file (for example, how does symfony https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md)

**Comment by mikaelcom** [comment]
Thanks for your quick advice!

I'll wait until April 19th at least to create this next release I think.

So anybody is welcome to share its advice or even his wishlist of new features within this next release 😉

**Comment by mikaelcom** [comment]
done 😄, release [2.7.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.7.0) is now available
