### ISSUE TITLE
Improve the Readme

### ISSUE THREAD

**Issue by mikaelcom** [WsdlToPhp/PackageGenerator#96]
The feedback from #95 shows that the readme file could be improved,
It seems to me that this [template](https://github.com/dbader/readme-template) is sufficient enough to provide the basic information about a library.

In addition, specific use cases can be written under the Wiki in order to provide more explicit samples.

**Comment by mikaelcom** [comment]
In addition to the readme refreshment, the wiki has been reviewed and the [Options page](https://github.com/WsdlToPhp/PackageGenerator/wiki/Options) has been created in order to explicit each option, feedbacks are welcome

**Comment by Gemorroj** [comment]
Changes are in branch [feature/issue-96](/WsdlToPhp/PackageGenerator/tree/feature/issue-96)

**Comment by mikaelcom** [comment]
fixed in [2.8.0](https://github.com/WsdlToPhp/PackageGenerator/releases/tag/2.8.0)
